// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.0.1         [262145]
ROOT Release   : 5.24/00       [333824]
Creator        : twig
Date           : Thu Dec 10 10:40:29 2009
Host           : Darwin dyn1205-245.wlan.ic.ac.uk 10.0.0 Darwin Kernel Version 10.0.0: Fri Jul 31 22:47:34 PDT 2009; root:xnu-1456.1.25~1/RELEASE_I386 i386
Dir            : /Users/twig/gbmsci/tmva
Training events: 11436
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "0.000000e+00" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
lv_met_Et                     lv_met_Et                     lv_met_Et                     lv_met_Et                                                       'F'    [0.0869567543268,1045.86328125]
lv_electron_Et                lv_electron_Et                lv_electron_Et                lv_electron_Et                                                  'F'    [15.0049276352,281.077362061]
lv_tau_Et                     lv_tau_Et                     lv_tau_Et                     lv_tau_Et                                                       'F'    [20.010427475,1279.53515625]
dphielectau                   dphielectau                   dphielectau                   dphielectau                                                     'F'    [0.00320380693302,3.14147591591]
dphielecmet                   dphielecmet                   dphielecmet                   dphielecmet                                                     'F'    [1.66893005371e-05,3.14120411873]
mtelecmet                     mtelecmet                     mtelecmet                     mtelecmet                                                       'F'    [0.000435188296251,341.258880615]
electronEcalIso               electronEcalIso               electronEcalIso               electronEcalIso                                                 'F'    [0,36.0478668213]
electronTrackIso              electronTrackIso              electronTrackIso              electronTrackIso                                                'F'    [0,69.3650665283]
tauTrack                      tauTrack                      tauTrack                      tauTrack                                                        'I'    [0,9]
tauLeadTrk                    tauLeadTrk                    tauLeadTrk                    tauLeadTrk                                                      'I'    [0,1]
tauECALIso                    tauECALIso                    tauECALIso                    tauECALIso                                                      'I'    [0,1]
tauElectron                   tauElectron                   tauElectron                   tauElectron                                                     'I'    [0,1]
tauCharge                     tauCharge                     tauCharge                     tauCharge                                                       'I'    [-5,3]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lv_met_Et", "lv_electron_Et", "lv_tau_Et", "dphielectau", "dphielecmet", "mtelecmet", "electronEcalIso", "electronTrackIso", "tauTrack", "tauLeadTrk", "tauECALIso", "tauElectron", "tauCharge" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -2.36248342917547;
   fWeightMatrix0to1[1][0] = -2.0392547875474;
   fWeightMatrix0to1[2][0] = 2.41566008663303;
   fWeightMatrix0to1[3][0] = -1.42899989547899;
   fWeightMatrix0to1[4][0] = 1.83644757436392;
   fWeightMatrix0to1[5][0] = -0.862712522933825;
   fWeightMatrix0to1[6][0] = 0.622837541356818;
   fWeightMatrix0to1[7][0] = 0.624934480951738;
   fWeightMatrix0to1[8][0] = 0.603006853678857;
   fWeightMatrix0to1[9][0] = 1.35835823746542;
   fWeightMatrix0to1[10][0] = -1.82298065703217;
   fWeightMatrix0to1[11][0] = -0.768351001337521;
   fWeightMatrix0to1[12][0] = 0.634255175365171;
   fWeightMatrix0to1[13][0] = 0.524713614508043;
   fWeightMatrix0to1[14][0] = 1.46498304073835;
   fWeightMatrix0to1[15][0] = -0.0950647221289225;
   fWeightMatrix0to1[16][0] = -0.210011907064734;
   fWeightMatrix0to1[17][0] = 1.86591685202809;
   fWeightMatrix0to1[0][1] = -1.26008761369208;
   fWeightMatrix0to1[1][1] = -1.44404798791699;
   fWeightMatrix0to1[2][1] = 1.75269313898458;
   fWeightMatrix0to1[3][1] = -0.461036267976774;
   fWeightMatrix0to1[4][1] = 0.932635559703971;
   fWeightMatrix0to1[5][1] = -1.56304917698232;
   fWeightMatrix0to1[6][1] = -0.604441546253821;
   fWeightMatrix0to1[7][1] = 0.114805158829212;
   fWeightMatrix0to1[8][1] = 1.92892192245873;
   fWeightMatrix0to1[9][1] = -2.09037993916046;
   fWeightMatrix0to1[10][1] = -1.57083141004592;
   fWeightMatrix0to1[11][1] = -0.884061144092438;
   fWeightMatrix0to1[12][1] = -1.0668593308215;
   fWeightMatrix0to1[13][1] = 1.16535195022416;
   fWeightMatrix0to1[14][1] = -1.14036404949029;
   fWeightMatrix0to1[15][1] = 1.62904950335643;
   fWeightMatrix0to1[16][1] = 0.830015387386631;
   fWeightMatrix0to1[17][1] = 0.732362472302738;
   fWeightMatrix0to1[0][2] = -1.78184567777118;
   fWeightMatrix0to1[1][2] = -1.67364179518659;
   fWeightMatrix0to1[2][2] = 1.36354446143257;
   fWeightMatrix0to1[3][2] = 2.04537468695182;
   fWeightMatrix0to1[4][2] = 1.24227803008327;
   fWeightMatrix0to1[5][2] = 1.12359028989196;
   fWeightMatrix0to1[6][2] = -1.97798826621121;
   fWeightMatrix0to1[7][2] = 1.37126733627605;
   fWeightMatrix0to1[8][2] = -0.0855689747788494;
   fWeightMatrix0to1[9][2] = 0.166785632356143;
   fWeightMatrix0to1[10][2] = -0.549974375397193;
   fWeightMatrix0to1[11][2] = 1.55603587843263;
   fWeightMatrix0to1[12][2] = 1.94620297217853;
   fWeightMatrix0to1[13][2] = -0.891272868682212;
   fWeightMatrix0to1[14][2] = -1.21891855453679;
   fWeightMatrix0to1[15][2] = -2.07227235135899;
   fWeightMatrix0to1[16][2] = 1.27907581646101;
   fWeightMatrix0to1[17][2] = -1.58063719300976;
   fWeightMatrix0to1[0][3] = 1.43975366598778;
   fWeightMatrix0to1[1][3] = -0.20324018859759;
   fWeightMatrix0to1[2][3] = -0.00335846477629769;
   fWeightMatrix0to1[3][3] = -0.736319643642155;
   fWeightMatrix0to1[4][3] = 0.0779877695786786;
   fWeightMatrix0to1[5][3] = 0.677753143191714;
   fWeightMatrix0to1[6][3] = -0.317509109322105;
   fWeightMatrix0to1[7][3] = 0.877490091579214;
   fWeightMatrix0to1[8][3] = 1.55888885900783;
   fWeightMatrix0to1[9][3] = -0.367060110639365;
   fWeightMatrix0to1[10][3] = -0.107153169451988;
   fWeightMatrix0to1[11][3] = 1.37086088517345;
   fWeightMatrix0to1[12][3] = -1.18857077132381;
   fWeightMatrix0to1[13][3] = -1.37772407033059;
   fWeightMatrix0to1[14][3] = -1.42194627834344;
   fWeightMatrix0to1[15][3] = -1.54085653186472;
   fWeightMatrix0to1[16][3] = -0.498750982092851;
   fWeightMatrix0to1[17][3] = 1.76470347151847;
   fWeightMatrix0to1[0][4] = 0.0086892773044197;
   fWeightMatrix0to1[1][4] = 0.552198317750697;
   fWeightMatrix0to1[2][4] = 0.692752504463576;
   fWeightMatrix0to1[3][4] = -0.282045920749748;
   fWeightMatrix0to1[4][4] = -0.492064036620824;
   fWeightMatrix0to1[5][4] = 0.684708933966942;
   fWeightMatrix0to1[6][4] = -0.0926631639656288;
   fWeightMatrix0to1[7][4] = 0.560579617247045;
   fWeightMatrix0to1[8][4] = -1.4158757597366;
   fWeightMatrix0to1[9][4] = 1.1362187930314;
   fWeightMatrix0to1[10][4] = 0.62156641991163;
   fWeightMatrix0to1[11][4] = -0.0386144716181844;
   fWeightMatrix0to1[12][4] = -0.308741693897478;
   fWeightMatrix0to1[13][4] = -0.246294188437201;
   fWeightMatrix0to1[14][4] = -0.326999846068731;
   fWeightMatrix0to1[15][4] = -1.87093088916996;
   fWeightMatrix0to1[16][4] = -0.377756043481133;
   fWeightMatrix0to1[17][4] = 1.4951774801952;
   fWeightMatrix0to1[0][5] = 0.630071191000369;
   fWeightMatrix0to1[1][5] = -0.614097172377356;
   fWeightMatrix0to1[2][5] = -1.55627601649882;
   fWeightMatrix0to1[3][5] = 1.66643269425918;
   fWeightMatrix0to1[4][5] = 2.03047648952952;
   fWeightMatrix0to1[5][5] = -1.44404638539083;
   fWeightMatrix0to1[6][5] = -0.926919871884713;
   fWeightMatrix0to1[7][5] = -1.88917183112748;
   fWeightMatrix0to1[8][5] = -1.01637965065623;
   fWeightMatrix0to1[9][5] = -1.74611796140453;
   fWeightMatrix0to1[10][5] = 1.25836939810792;
   fWeightMatrix0to1[11][5] = -0.78801228195057;
   fWeightMatrix0to1[12][5] = 0.622463484936979;
   fWeightMatrix0to1[13][5] = -1.08926785573852;
   fWeightMatrix0to1[14][5] = 1.03601364228084;
   fWeightMatrix0to1[15][5] = 0.441963506739688;
   fWeightMatrix0to1[16][5] = -1.3367018851106;
   fWeightMatrix0to1[17][5] = 1.82372253139442;
   fWeightMatrix0to1[0][6] = -1.61231324212785;
   fWeightMatrix0to1[1][6] = -1.82182179659213;
   fWeightMatrix0to1[2][6] = 0.723521569142253;
   fWeightMatrix0to1[3][6] = -0.939927442095165;
   fWeightMatrix0to1[4][6] = 0.906679179604175;
   fWeightMatrix0to1[5][6] = -0.872423421634029;
   fWeightMatrix0to1[6][6] = 0.377660858101108;
   fWeightMatrix0to1[7][6] = 0.634192086192431;
   fWeightMatrix0to1[8][6] = -1.49237110645915;
   fWeightMatrix0to1[9][6] = -1.12698067756185;
   fWeightMatrix0to1[10][6] = -1.58778719233164;
   fWeightMatrix0to1[11][6] = 0.859361987197416;
   fWeightMatrix0to1[12][6] = -1.56230941053042;
   fWeightMatrix0to1[13][6] = -1.21045018160624;
   fWeightMatrix0to1[14][6] = -1.61053219889378;
   fWeightMatrix0to1[15][6] = 1.38294416332433;
   fWeightMatrix0to1[16][6] = -0.553216412945555;
   fWeightMatrix0to1[17][6] = -1.5859241803573;
   fWeightMatrix0to1[0][7] = 1.37840941376662;
   fWeightMatrix0to1[1][7] = -0.255630959826445;
   fWeightMatrix0to1[2][7] = 1.30486241612153;
   fWeightMatrix0to1[3][7] = -1.36038660174125;
   fWeightMatrix0to1[4][7] = -0.370592527069215;
   fWeightMatrix0to1[5][7] = -1.35675498086485;
   fWeightMatrix0to1[6][7] = 0.12014098033026;
   fWeightMatrix0to1[7][7] = -2.00238342204143;
   fWeightMatrix0to1[8][7] = -0.750072130365652;
   fWeightMatrix0to1[9][7] = 1.76450980328948;
   fWeightMatrix0to1[10][7] = -1.27474317893893;
   fWeightMatrix0to1[11][7] = 0.281508388055064;
   fWeightMatrix0to1[12][7] = -0.943150895289832;
   fWeightMatrix0to1[13][7] = -1.11663083017652;
   fWeightMatrix0to1[14][7] = 1.942223911967;
   fWeightMatrix0to1[15][7] = -0.730805285821355;
   fWeightMatrix0to1[16][7] = -0.748525916135073;
   fWeightMatrix0to1[17][7] = -0.473928986873119;
   fWeightMatrix0to1[0][8] = 0.813923897220272;
   fWeightMatrix0to1[1][8] = 0.556218070678142;
   fWeightMatrix0to1[2][8] = 0.780310938532301;
   fWeightMatrix0to1[3][8] = 0.990930908722048;
   fWeightMatrix0to1[4][8] = 1.1273165286772;
   fWeightMatrix0to1[5][8] = -1.73521897363463;
   fWeightMatrix0to1[6][8] = 1.4578119504194;
   fWeightMatrix0to1[7][8] = -1.5205707517275;
   fWeightMatrix0to1[8][8] = -1.05868127840085;
   fWeightMatrix0to1[9][8] = 0.515872026512082;
   fWeightMatrix0to1[10][8] = 0.189606856115032;
   fWeightMatrix0to1[11][8] = -0.230411555988011;
   fWeightMatrix0to1[12][8] = 0.968664411451566;
   fWeightMatrix0to1[13][8] = -0.990581563741134;
   fWeightMatrix0to1[14][8] = -0.457000791292363;
   fWeightMatrix0to1[15][8] = 0.747946677324951;
   fWeightMatrix0to1[16][8] = 1.65373938280251;
   fWeightMatrix0to1[17][8] = -0.162986512479316;
   fWeightMatrix0to1[0][9] = 0.0710226138568537;
   fWeightMatrix0to1[1][9] = 1.11443808870701;
   fWeightMatrix0to1[2][9] = -1.03262647970923;
   fWeightMatrix0to1[3][9] = -0.757327438000559;
   fWeightMatrix0to1[4][9] = -0.268969718468328;
   fWeightMatrix0to1[5][9] = -0.0750019123099864;
   fWeightMatrix0to1[6][9] = -1.4166826642488;
   fWeightMatrix0to1[7][9] = -1.5100525535466;
   fWeightMatrix0to1[8][9] = -1.20739707639779;
   fWeightMatrix0to1[9][9] = 0.863018231553583;
   fWeightMatrix0to1[10][9] = 0.814047834546801;
   fWeightMatrix0to1[11][9] = 0.319295625351601;
   fWeightMatrix0to1[12][9] = 0.63473740009992;
   fWeightMatrix0to1[13][9] = -1.60576523487489;
   fWeightMatrix0to1[14][9] = -0.252016438988552;
   fWeightMatrix0to1[15][9] = -0.110346912971911;
   fWeightMatrix0to1[16][9] = -0.247200502310105;
   fWeightMatrix0to1[17][9] = 1.44914932190325;
   fWeightMatrix0to1[0][10] = -1.50302820596955;
   fWeightMatrix0to1[1][10] = 0.832658569987376;
   fWeightMatrix0to1[2][10] = -0.873353904435909;
   fWeightMatrix0to1[3][10] = -0.207306272042643;
   fWeightMatrix0to1[4][10] = 0.252497204452124;
   fWeightMatrix0to1[5][10] = 1.10827640251584;
   fWeightMatrix0to1[6][10] = -1.01846684857602;
   fWeightMatrix0to1[7][10] = -0.23027353905299;
   fWeightMatrix0to1[8][10] = -0.793402811953724;
   fWeightMatrix0to1[9][10] = -0.401433464748542;
   fWeightMatrix0to1[10][10] = 0.154514389702769;
   fWeightMatrix0to1[11][10] = 1.33191378514593;
   fWeightMatrix0to1[12][10] = 0.274549579837813;
   fWeightMatrix0to1[13][10] = -0.0369526280675567;
   fWeightMatrix0to1[14][10] = -0.117362807431183;
   fWeightMatrix0to1[15][10] = 0.171215248730048;
   fWeightMatrix0to1[16][10] = -0.0142684094570035;
   fWeightMatrix0to1[17][10] = -0.17653820316478;
   fWeightMatrix0to1[0][11] = -0.682369547943907;
   fWeightMatrix0to1[1][11] = -0.366388213529689;
   fWeightMatrix0to1[2][11] = -0.1958391162634;
   fWeightMatrix0to1[3][11] = 0.615417408059372;
   fWeightMatrix0to1[4][11] = 0.615547005842349;
   fWeightMatrix0to1[5][11] = -1.26388890968806;
   fWeightMatrix0to1[6][11] = -1.14090640535236;
   fWeightMatrix0to1[7][11] = -0.409213586875743;
   fWeightMatrix0to1[8][11] = -0.207989935608808;
   fWeightMatrix0to1[9][11] = -0.113820038778149;
   fWeightMatrix0to1[10][11] = 0.0942211011602143;
   fWeightMatrix0to1[11][11] = -0.337511811766443;
   fWeightMatrix0to1[12][11] = -0.8493765987661;
   fWeightMatrix0to1[13][11] = -0.170222359565595;
   fWeightMatrix0to1[14][11] = 0.529244464147314;
   fWeightMatrix0to1[15][11] = -0.952807302980029;
   fWeightMatrix0to1[16][11] = -0.184699831888419;
   fWeightMatrix0to1[17][11] = 0.245445326128466;
   fWeightMatrix0to1[0][12] = 1.1384606915898;
   fWeightMatrix0to1[1][12] = 1.54873648097439;
   fWeightMatrix0to1[2][12] = -0.965613490455811;
   fWeightMatrix0to1[3][12] = -0.763968660976167;
   fWeightMatrix0to1[4][12] = 1.51457052191159;
   fWeightMatrix0to1[5][12] = 0.317418035000626;
   fWeightMatrix0to1[6][12] = -1.10414601170271;
   fWeightMatrix0to1[7][12] = -0.951115662125621;
   fWeightMatrix0to1[8][12] = -1.1233754511306;
   fWeightMatrix0to1[9][12] = 0.458637297529104;
   fWeightMatrix0to1[10][12] = 0.419146904423946;
   fWeightMatrix0to1[11][12] = -1.68413137778198;
   fWeightMatrix0to1[12][12] = -1.63663824203949;
   fWeightMatrix0to1[13][12] = 0.249864200610721;
   fWeightMatrix0to1[14][12] = -1.30504547405943;
   fWeightMatrix0to1[15][12] = -0.562506090004664;
   fWeightMatrix0to1[16][12] = 0.275718671736642;
   fWeightMatrix0to1[17][12] = -0.231679432472505;
   fWeightMatrix0to1[0][13] = 1.86630298865048;
   fWeightMatrix0to1[1][13] = -1.57769580838587;
   fWeightMatrix0to1[2][13] = 0.923580104866882;
   fWeightMatrix0to1[3][13] = 0.862944453699449;
   fWeightMatrix0to1[4][13] = -0.398818658423915;
   fWeightMatrix0to1[5][13] = 2.06042007665363;
   fWeightMatrix0to1[6][13] = 0.538473029722375;
   fWeightMatrix0to1[7][13] = -0.310807723046819;
   fWeightMatrix0to1[8][13] = -1.02439836874931;
   fWeightMatrix0to1[9][13] = -0.703995067028517;
   fWeightMatrix0to1[10][13] = -0.266078183644276;
   fWeightMatrix0to1[11][13] = 1.26174171598114;
   fWeightMatrix0to1[12][13] = 1.84434607830696;
   fWeightMatrix0to1[13][13] = -0.741541067447207;
   fWeightMatrix0to1[14][13] = 1.38041388337571;
   fWeightMatrix0to1[15][13] = 0.786579312513398;
   fWeightMatrix0to1[16][13] = 0.464199283471163;
   fWeightMatrix0to1[17][13] = -1.3650458347343;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.985217524513346;
   fWeightMatrix1to2[0][1] = 1.2951657336567;
   fWeightMatrix1to2[0][2] = 0.744766093703001;
   fWeightMatrix1to2[0][3] = 0.0302012349924367;
   fWeightMatrix1to2[0][4] = -0.911247066238337;
   fWeightMatrix1to2[0][5] = -0.719265716453643;
   fWeightMatrix1to2[0][6] = 0.00532330401433518;
   fWeightMatrix1to2[0][7] = -0.032329886083527;
   fWeightMatrix1to2[0][8] = 0.0118904044061141;
   fWeightMatrix1to2[0][9] = 0.0385400157653652;
   fWeightMatrix1to2[0][10] = -0.595738692095973;
   fWeightMatrix1to2[0][11] = 0.0180618636260866;
   fWeightMatrix1to2[0][12] = -0.0190172198623522;
   fWeightMatrix1to2[0][13] = 0.0111794447880295;
   fWeightMatrix1to2[0][14] = -0.00279518428165083;
   fWeightMatrix1to2[0][15] = 0.0491411185763908;
   fWeightMatrix1to2[0][16] = -0.0426752370633774;
   fWeightMatrix1to2[0][17] = 0.0037800431459397;
   fWeightMatrix1to2[0][18] = -0.0768433452650365;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0.623785734177;
   fMax_1[0][0] = 248.311645508;
   fMin_1[1][0] = 0.0869567543268;
   fMax_1[1][0] = 1045.86328125;
   fMin_1[2][0] = 0.0869567543268;
   fMax_1[2][0] = 1045.86328125;
   fMin_1[0][1] = 15.0250597;
   fMax_1[0][1] = 101.359306335;
   fMin_1[1][1] = 15.0049276352;
   fMax_1[1][1] = 281.077362061;
   fMin_1[2][1] = 15.0049276352;
   fMax_1[2][1] = 281.077362061;
   fMin_1[0][2] = 20.1829204559;
   fMax_1[0][2] = 235.90536499;
   fMin_1[1][2] = 20.010427475;
   fMax_1[1][2] = 1279.53515625;
   fMin_1[2][2] = 20.010427475;
   fMax_1[2][2] = 1279.53515625;
   fMin_1[0][3] = 0.0114453295246;
   fMax_1[0][3] = 3.1414437294;
   fMin_1[1][3] = 0.00320380693302;
   fMax_1[1][3] = 3.14147591591;
   fMin_1[2][3] = 0.00320380693302;
   fMax_1[2][3] = 3.14147591591;
   fMin_1[0][4] = 0.0033310353756;
   fMax_1[0][4] = 3.13841199875;
   fMin_1[1][4] = 1.66893005371e-05;
   fMax_1[1][4] = 3.14120411873;
   fMin_1[2][4] = 1.66893005371e-05;
   fMax_1[2][4] = 3.14120411873;
   fMin_1[0][5] = 0.0888140574098;
   fMax_1[0][5] = 102.552612305;
   fMin_1[1][5] = 0.000435188296251;
   fMax_1[1][5] = 341.258880615;
   fMin_1[2][5] = 0.000435188296251;
   fMax_1[2][5] = 341.258880615;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 14.1990718842;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 36.0478668213;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 36.0478668213;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 18.4750328064;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 69.3650665283;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 69.3650665283;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 9;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 9;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 9;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = -3;
   fMax_1[0][12] = 3;
   fMin_1[1][12] = -5;
   fMax_1[1][12] = 3;
   fMin_1[2][12] = -5;
   fMax_1[2][12] = 3;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
