// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.0.1         [262145]
ROOT Release   : 5.24/00       [333824]
Creator        : twig
Date           : Thu Dec 10 10:46:44 2009
Host           : Darwin dyn1205-245.wlan.ic.ac.uk 10.0.0 Darwin Kernel Version 10.0.0: Fri Jul 31 22:47:34 PDT 2009; root:xnu-1456.1.25~1/RELEASE_I386 i386
Dir            : /Users/twig/gbmsci/tmva
Training events: 11436
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "0.000000e+00" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
lv_met_Et                     lv_met_Et                     lv_met_Et                     lv_met_Et                                                       'F'    [0.117894597352,58682.0507812]
lv_electron_Et                lv_electron_Et                lv_electron_Et                lv_electron_Et                                                  'F'    [15.0001068115,446.446594238]
lv_tau_Et                     lv_tau_Et                     lv_tau_Et                     lv_tau_Et                                                       'F'    [20.0247249603,897.134277344]
dphielectau                   dphielectau                   dphielectau                   dphielectau                                                     'F'    [0.0114453295246,3.14147591591]
dphielecmet                   dphielecmet                   dphielecmet                   dphielecmet                                                     'F'    [1.66893005371e-05,3.14153695107]
mtelecmet                     mtelecmet                     mtelecmet                     mtelecmet                                                       'F'    [0.000661026162561,3124.58056641]
electronEcalIso               electronEcalIso               electronEcalIso               electronEcalIso                                                 'F'    [0,103.247169495]
electronTrackIso              electronTrackIso              electronTrackIso              electronTrackIso                                                'F'    [0,89.6219711304]
tauTrack                      tauTrack                      tauTrack                      tauTrack                                                        'I'    [0,11]
tauLeadTrk                    tauLeadTrk                    tauLeadTrk                    tauLeadTrk                                                      'I'    [0,1]
tauECALIso                    tauECALIso                    tauECALIso                    tauECALIso                                                      'I'    [0,1]
tauElectron                   tauElectron                   tauElectron                   tauElectron                                                     'I'    [0,1]
tauCharge                     tauCharge                     tauCharge                     tauCharge                                                       'I'    [-5,4]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lv_met_Et", "lv_electron_Et", "lv_tau_Et", "dphielectau", "dphielecmet", "mtelecmet", "electronEcalIso", "electronTrackIso", "tauTrack", "tauLeadTrk", "tauECALIso", "tauElectron", "tauCharge" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.3361457024627;
   fWeightMatrix0to1[1][0] = -0.2468861199134;
   fWeightMatrix0to1[2][0] = -0.538930307010681;
   fWeightMatrix0to1[3][0] = -0.161622933391392;
   fWeightMatrix0to1[4][0] = 0.941685743653036;
   fWeightMatrix0to1[5][0] = -1.03153326608349;
   fWeightMatrix0to1[6][0] = 0.566077027388281;
   fWeightMatrix0to1[7][0] = 1.92849347093768;
   fWeightMatrix0to1[8][0] = -0.903051772464803;
   fWeightMatrix0to1[9][0] = 0.506950329557927;
   fWeightMatrix0to1[10][0] = 0.798324321510225;
   fWeightMatrix0to1[11][0] = -0.136092606599761;
   fWeightMatrix0to1[12][0] = 0.633960377009441;
   fWeightMatrix0to1[13][0] = 0.47941575417188;
   fWeightMatrix0to1[14][0] = -0.319381832873433;
   fWeightMatrix0to1[15][0] = -0.879124092356235;
   fWeightMatrix0to1[16][0] = 1.01355329794195;
   fWeightMatrix0to1[17][0] = -1.005118966582;
   fWeightMatrix0to1[0][1] = 1.7280559477474;
   fWeightMatrix0to1[1][1] = 1.75891375343573;
   fWeightMatrix0to1[2][1] = 0.604318024540724;
   fWeightMatrix0to1[3][1] = 1.60213109586557;
   fWeightMatrix0to1[4][1] = -0.764315029679889;
   fWeightMatrix0to1[5][1] = 0.66902324075049;
   fWeightMatrix0to1[6][1] = 0.5920389984844;
   fWeightMatrix0to1[7][1] = -1.63149503195088;
   fWeightMatrix0to1[8][1] = -0.951244510327063;
   fWeightMatrix0to1[9][1] = -0.83738839967776;
   fWeightMatrix0to1[10][1] = -0.782667205932581;
   fWeightMatrix0to1[11][1] = 2.08435203539546;
   fWeightMatrix0to1[12][1] = -1.40058888008479;
   fWeightMatrix0to1[13][1] = 0.997118063655027;
   fWeightMatrix0to1[14][1] = -1.98302877007985;
   fWeightMatrix0to1[15][1] = 0.587298101319918;
   fWeightMatrix0to1[16][1] = -0.689083938867195;
   fWeightMatrix0to1[17][1] = -0.605955186973535;
   fWeightMatrix0to1[0][2] = 1.20832899226149;
   fWeightMatrix0to1[1][2] = 1.78250949356651;
   fWeightMatrix0to1[2][2] = -0.980414876848998;
   fWeightMatrix0to1[3][2] = 1.07140088932019;
   fWeightMatrix0to1[4][2] = -0.783039938620832;
   fWeightMatrix0to1[5][2] = 0.973280380671555;
   fWeightMatrix0to1[6][2] = 0.597517893561408;
   fWeightMatrix0to1[7][2] = 0.919323106862362;
   fWeightMatrix0to1[8][2] = -1.02172843390595;
   fWeightMatrix0to1[9][2] = -1.47074424579245;
   fWeightMatrix0to1[10][2] = -1.0590233586632;
   fWeightMatrix0to1[11][2] = -1.08298292515395;
   fWeightMatrix0to1[12][2] = -0.693687185618512;
   fWeightMatrix0to1[13][2] = 0.894509019033297;
   fWeightMatrix0to1[14][2] = 1.63069180604137;
   fWeightMatrix0to1[15][2] = -0.464396161260125;
   fWeightMatrix0to1[16][2] = -0.68710934651717;
   fWeightMatrix0to1[17][2] = -0.127618520167297;
   fWeightMatrix0to1[0][3] = -1.62719271754236;
   fWeightMatrix0to1[1][3] = -0.799796804540957;
   fWeightMatrix0to1[2][3] = -0.289993786119734;
   fWeightMatrix0to1[3][3] = -0.692779668501326;
   fWeightMatrix0to1[4][3] = -1.3621221584603;
   fWeightMatrix0to1[5][3] = -1.86370530406225;
   fWeightMatrix0to1[6][3] = -0.5778528948576;
   fWeightMatrix0to1[7][3] = 0.0580890382029;
   fWeightMatrix0to1[8][3] = -0.949463829095611;
   fWeightMatrix0to1[9][3] = 0.775478258125686;
   fWeightMatrix0to1[10][3] = 0.0080061249629138;
   fWeightMatrix0to1[11][3] = 1.31339406187646;
   fWeightMatrix0to1[12][3] = 0.519687343958939;
   fWeightMatrix0to1[13][3] = -0.498513580848665;
   fWeightMatrix0to1[14][3] = -0.233192953085889;
   fWeightMatrix0to1[15][3] = -0.441885269748365;
   fWeightMatrix0to1[16][3] = 2.03872366968195;
   fWeightMatrix0to1[17][3] = -1.34619332356552;
   fWeightMatrix0to1[0][4] = -0.648921886876639;
   fWeightMatrix0to1[1][4] = -0.179460222143645;
   fWeightMatrix0to1[2][4] = 0.0283040203455966;
   fWeightMatrix0to1[3][4] = 0.812898459920877;
   fWeightMatrix0to1[4][4] = -0.26114482145577;
   fWeightMatrix0to1[5][4] = -0.182852619064409;
   fWeightMatrix0to1[6][4] = -0.312406559966321;
   fWeightMatrix0to1[7][4] = -0.252076825908525;
   fWeightMatrix0to1[8][4] = -0.177425075657239;
   fWeightMatrix0to1[9][4] = 0.0366735108877725;
   fWeightMatrix0to1[10][4] = 0.1210026737951;
   fWeightMatrix0to1[11][4] = 0.751648045486611;
   fWeightMatrix0to1[12][4] = 1.6601593780778;
   fWeightMatrix0to1[13][4] = -0.903154059194138;
   fWeightMatrix0to1[14][4] = 0.399659849806623;
   fWeightMatrix0to1[15][4] = -0.101556839818299;
   fWeightMatrix0to1[16][4] = 1.42572359355034;
   fWeightMatrix0to1[17][4] = -1.48611612048788;
   fWeightMatrix0to1[0][5] = -0.572948231928767;
   fWeightMatrix0to1[1][5] = 0.0514280122640002;
   fWeightMatrix0to1[2][5] = -0.487392006266055;
   fWeightMatrix0to1[3][5] = -1.76542596082355;
   fWeightMatrix0to1[4][5] = -1.51944205657435;
   fWeightMatrix0to1[5][5] = -1.27192552143011;
   fWeightMatrix0to1[6][5] = 1.84511553119489;
   fWeightMatrix0to1[7][5] = 1.28469029663304;
   fWeightMatrix0to1[8][5] = -1.59342597478219;
   fWeightMatrix0to1[9][5] = -0.092616934063447;
   fWeightMatrix0to1[10][5] = 1.43093314052251;
   fWeightMatrix0to1[11][5] = 2.10834087288054;
   fWeightMatrix0to1[12][5] = -1.95008737423676;
   fWeightMatrix0to1[13][5] = 1.5121675927513;
   fWeightMatrix0to1[14][5] = -0.409985242336959;
   fWeightMatrix0to1[15][5] = -0.53879861062179;
   fWeightMatrix0to1[16][5] = 2.11446985564813;
   fWeightMatrix0to1[17][5] = 0.301510971105798;
   fWeightMatrix0to1[0][6] = 1.66180376514151;
   fWeightMatrix0to1[1][6] = -1.27597732190288;
   fWeightMatrix0to1[2][6] = -1.68081752457589;
   fWeightMatrix0to1[3][6] = -1.8210215398272;
   fWeightMatrix0to1[4][6] = 0.662739012167432;
   fWeightMatrix0to1[5][6] = -0.357939386628295;
   fWeightMatrix0to1[6][6] = -1.17445847398303;
   fWeightMatrix0to1[7][6] = 1.74901449766427;
   fWeightMatrix0to1[8][6] = 0.899650839012689;
   fWeightMatrix0to1[9][6] = -1.45802282247185;
   fWeightMatrix0to1[10][6] = 0.63404347466687;
   fWeightMatrix0to1[11][6] = 2.0116674160581;
   fWeightMatrix0to1[12][6] = -0.19704787605064;
   fWeightMatrix0to1[13][6] = 1.74362237748512;
   fWeightMatrix0to1[14][6] = 0.893721475926199;
   fWeightMatrix0to1[15][6] = -0.0754219474931631;
   fWeightMatrix0to1[16][6] = -0.672851608876199;
   fWeightMatrix0to1[17][6] = 1.06486688179529;
   fWeightMatrix0to1[0][7] = 1.87872500228438;
   fWeightMatrix0to1[1][7] = 0.324096336063487;
   fWeightMatrix0to1[2][7] = 0.950111923653967;
   fWeightMatrix0to1[3][7] = -1.08448639732447;
   fWeightMatrix0to1[4][7] = 0.908580402281292;
   fWeightMatrix0to1[5][7] = 0.311277211042899;
   fWeightMatrix0to1[6][7] = -0.535353569822518;
   fWeightMatrix0to1[7][7] = 1.61303177579172;
   fWeightMatrix0to1[8][7] = -0.627676372133527;
   fWeightMatrix0to1[9][7] = -1.41443741828836;
   fWeightMatrix0to1[10][7] = -0.562471342873291;
   fWeightMatrix0to1[11][7] = 1.49778870670162;
   fWeightMatrix0to1[12][7] = -0.937213866505752;
   fWeightMatrix0to1[13][7] = -1.27256933147774;
   fWeightMatrix0to1[14][7] = 1.10664699379531;
   fWeightMatrix0to1[15][7] = 0.60616094529076;
   fWeightMatrix0to1[16][7] = -0.518983145335273;
   fWeightMatrix0to1[17][7] = 0.161869177362757;
   fWeightMatrix0to1[0][8] = 0.754307882233444;
   fWeightMatrix0to1[1][8] = -1.28682415954634;
   fWeightMatrix0to1[2][8] = -0.979734890301557;
   fWeightMatrix0to1[3][8] = 0.304913336387754;
   fWeightMatrix0to1[4][8] = -1.37552727889097;
   fWeightMatrix0to1[5][8] = 0.29334050111512;
   fWeightMatrix0to1[6][8] = 1.01538664097984;
   fWeightMatrix0to1[7][8] = 0.777174700025383;
   fWeightMatrix0to1[8][8] = 2.17440145333709;
   fWeightMatrix0to1[9][8] = -1.45311255953679;
   fWeightMatrix0to1[10][8] = 0.620109390497771;
   fWeightMatrix0to1[11][8] = -1.34792929580946;
   fWeightMatrix0to1[12][8] = -1.30209167407619;
   fWeightMatrix0to1[13][8] = 0.603950176766271;
   fWeightMatrix0to1[14][8] = -0.496857738437788;
   fWeightMatrix0to1[15][8] = -0.59042188796141;
   fWeightMatrix0to1[16][8] = 0.223808924049633;
   fWeightMatrix0to1[17][8] = -1.77592573363121;
   fWeightMatrix0to1[0][9] = 1.15588917008912;
   fWeightMatrix0to1[1][9] = 1.68212784967561;
   fWeightMatrix0to1[2][9] = -1.89885764417513;
   fWeightMatrix0to1[3][9] = -0.14427225346966;
   fWeightMatrix0to1[4][9] = 0.0470782913095143;
   fWeightMatrix0to1[5][9] = -1.09362299047818;
   fWeightMatrix0to1[6][9] = 1.42052272133364;
   fWeightMatrix0to1[7][9] = 1.44756541068396;
   fWeightMatrix0to1[8][9] = 0.0817405842633059;
   fWeightMatrix0to1[9][9] = -0.927339477947916;
   fWeightMatrix0to1[10][9] = 0.16171200189208;
   fWeightMatrix0to1[11][9] = -0.416599191392673;
   fWeightMatrix0to1[12][9] = 0.687435249651254;
   fWeightMatrix0to1[13][9] = -2.27423714931829;
   fWeightMatrix0to1[14][9] = -1.2328290032306;
   fWeightMatrix0to1[15][9] = 2.24303602882518;
   fWeightMatrix0to1[16][9] = 0.104263297993312;
   fWeightMatrix0to1[17][9] = -0.260023721305254;
   fWeightMatrix0to1[0][10] = 1.50967010196814;
   fWeightMatrix0to1[1][10] = -0.0353421486886835;
   fWeightMatrix0to1[2][10] = -0.0760640269805187;
   fWeightMatrix0to1[3][10] = 0.0426041030727137;
   fWeightMatrix0to1[4][10] = -0.100172258162151;
   fWeightMatrix0to1[5][10] = -0.912893019533288;
   fWeightMatrix0to1[6][10] = -0.016847977078327;
   fWeightMatrix0to1[7][10] = -1.84850420602943;
   fWeightMatrix0to1[8][10] = 0.954234466544366;
   fWeightMatrix0to1[9][10] = 1.71382241616946;
   fWeightMatrix0to1[10][10] = -0.196469763359259;
   fWeightMatrix0to1[11][10] = 0.574541050967846;
   fWeightMatrix0to1[12][10] = -0.259570113374596;
   fWeightMatrix0to1[13][10] = -0.121297484178715;
   fWeightMatrix0to1[14][10] = 0.177895709722762;
   fWeightMatrix0to1[15][10] = -0.0947758226222121;
   fWeightMatrix0to1[16][10] = 1.15444340919356;
   fWeightMatrix0to1[17][10] = 1.48485112826274;
   fWeightMatrix0to1[0][11] = -0.498330541390686;
   fWeightMatrix0to1[1][11] = -1.3164996600652;
   fWeightMatrix0to1[2][11] = -1.48347521942025;
   fWeightMatrix0to1[3][11] = -1.64835724289372;
   fWeightMatrix0to1[4][11] = 1.01631480645969;
   fWeightMatrix0to1[5][11] = 2.1286850378921;
   fWeightMatrix0to1[6][11] = 0.0183818455998326;
   fWeightMatrix0to1[7][11] = -0.309840802304921;
   fWeightMatrix0to1[8][11] = 0.54266130007758;
   fWeightMatrix0to1[9][11] = 0.870404615880888;
   fWeightMatrix0to1[10][11] = -0.116694606774965;
   fWeightMatrix0to1[11][11] = -0.375557986234941;
   fWeightMatrix0to1[12][11] = 1.0714487737238;
   fWeightMatrix0to1[13][11] = 1.70786528580584;
   fWeightMatrix0to1[14][11] = 1.19045634891432;
   fWeightMatrix0to1[15][11] = -2.11361636866874;
   fWeightMatrix0to1[16][11] = -2.21717863886198;
   fWeightMatrix0to1[17][11] = -1.13778588639097;
   fWeightMatrix0to1[0][12] = -0.862846861144979;
   fWeightMatrix0to1[1][12] = -0.0126792482042821;
   fWeightMatrix0to1[2][12] = -0.453888950215183;
   fWeightMatrix0to1[3][12] = 0.155676100488719;
   fWeightMatrix0to1[4][12] = 0.41649374519123;
   fWeightMatrix0to1[5][12] = -0.80140568007315;
   fWeightMatrix0to1[6][12] = -1.73801114591626;
   fWeightMatrix0to1[7][12] = 0.0938442640019321;
   fWeightMatrix0to1[8][12] = 1.69296415657038;
   fWeightMatrix0to1[9][12] = -0.254471583906686;
   fWeightMatrix0to1[10][12] = 0.258595143672415;
   fWeightMatrix0to1[11][12] = 0.209578606578605;
   fWeightMatrix0to1[12][12] = -1.36828677222954;
   fWeightMatrix0to1[13][12] = 0.339677972019585;
   fWeightMatrix0to1[14][12] = -0.272493193389747;
   fWeightMatrix0to1[15][12] = 0.580295142202542;
   fWeightMatrix0to1[16][12] = -0.0488397216478187;
   fWeightMatrix0to1[17][12] = -0.130302445766832;
   fWeightMatrix0to1[0][13] = -0.599140222404471;
   fWeightMatrix0to1[1][13] = 1.68297184155511;
   fWeightMatrix0to1[2][13] = 0.86935202200967;
   fWeightMatrix0to1[3][13] = 0.611577213411037;
   fWeightMatrix0to1[4][13] = -1.56522952395791;
   fWeightMatrix0to1[5][13] = 1.12439057874301;
   fWeightMatrix0to1[6][13] = 1.99028360493782;
   fWeightMatrix0to1[7][13] = -1.35086898737205;
   fWeightMatrix0to1[8][13] = -0.403413350477488;
   fWeightMatrix0to1[9][13] = -0.358686944456426;
   fWeightMatrix0to1[10][13] = 1.32947503164177;
   fWeightMatrix0to1[11][13] = -1.86285338535581;
   fWeightMatrix0to1[12][13] = -0.104387184469619;
   fWeightMatrix0to1[13][13] = 0.837728539478195;
   fWeightMatrix0to1[14][13] = 0.749482746123484;
   fWeightMatrix0to1[15][13] = -0.935053537520075;
   fWeightMatrix0to1[16][13] = 1.11864976388551;
   fWeightMatrix0to1[17][13] = -1.34074419937894;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.00401402243926777;
   fWeightMatrix1to2[0][1] = -0.00953931286418005;
   fWeightMatrix1to2[0][2] = 0.0242946962843392;
   fWeightMatrix1to2[0][3] = -0.0609430288547901;
   fWeightMatrix1to2[0][4] = 0.0269310029163484;
   fWeightMatrix1to2[0][5] = 0.018905514541074;
   fWeightMatrix1to2[0][6] = -0.0032960048617768;
   fWeightMatrix1to2[0][7] = 1.28033166858624;
   fWeightMatrix1to2[0][8] = 0.00811697120771923;
   fWeightMatrix1to2[0][9] = -0.107475499592796;
   fWeightMatrix1to2[0][10] = 0.0836419440465296;
   fWeightMatrix1to2[0][11] = 0.364238437146274;
   fWeightMatrix1to2[0][12] = 0.255721590770606;
   fWeightMatrix1to2[0][13] = 0.0249597516870936;
   fWeightMatrix1to2[0][14] = 4.8236748280712e-05;
   fWeightMatrix1to2[0][15] = 0.00479366839561167;
   fWeightMatrix1to2[0][16] = 0.0622997753064396;
   fWeightMatrix1to2[0][17] = 0.00529773703135238;
   fWeightMatrix1to2[0][18] = 0.577094441588116;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0.117894597352;
   fMax_1[0][0] = 58682.0507812;
   fMin_1[1][0] = 0.117894597352;
   fMax_1[1][0] = 58682.0507812;
   fMin_1[2][0] = 0.117894597352;
   fMax_1[2][0] = 58682.0507812;
   fMin_1[0][1] = 15.0001068115;
   fMax_1[0][1] = 446.446594238;
   fMin_1[1][1] = 15.0001068115;
   fMax_1[1][1] = 446.446594238;
   fMin_1[2][1] = 15.0001068115;
   fMax_1[2][1] = 446.446594238;
   fMin_1[0][2] = 20.0247249603;
   fMax_1[0][2] = 897.134277344;
   fMin_1[1][2] = 20.0247249603;
   fMax_1[1][2] = 897.134277344;
   fMin_1[2][2] = 20.0247249603;
   fMax_1[2][2] = 897.134277344;
   fMin_1[0][3] = 0.0114453295246;
   fMax_1[0][3] = 3.14147591591;
   fMin_1[1][3] = 0.0114453295246;
   fMax_1[1][3] = 3.14147591591;
   fMin_1[2][3] = 0.0114453295246;
   fMax_1[2][3] = 3.14147591591;
   fMin_1[0][4] = 1.66893005371e-05;
   fMax_1[0][4] = 3.14153695107;
   fMin_1[1][4] = 1.66893005371e-05;
   fMax_1[1][4] = 3.14153695107;
   fMin_1[2][4] = 1.66893005371e-05;
   fMax_1[2][4] = 3.14153695107;
   fMin_1[0][5] = 0.000661026162561;
   fMax_1[0][5] = 3124.58056641;
   fMin_1[1][5] = 0.000661026162561;
   fMax_1[1][5] = 3124.58056641;
   fMin_1[2][5] = 0.000661026162561;
   fMax_1[2][5] = 3124.58056641;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 103.247169495;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 103.247169495;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 103.247169495;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 89.6219711304;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 89.6219711304;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 89.6219711304;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 11;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 11;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = -5;
   fMax_1[0][12] = 4;
   fMin_1[1][12] = -5;
   fMax_1[1][12] = 4;
   fMin_1[2][12] = -5;
   fMax_1[2][12] = 4;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
