// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.0.1         [262145]
ROOT Release   : 5.24/00       [333824]
Creator        : twig
Date           : Thu Dec 10 10:52:56 2009
Host           : Darwin dyn1205-245.wlan.ic.ac.uk 10.0.0 Darwin Kernel Version 10.0.0: Fri Jul 31 22:47:34 PDT 2009; root:xnu-1456.1.25~1/RELEASE_I386 i386
Dir            : /Users/twig/gbmsci/tmva
Training events: 11436
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "0.000000e+00" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
lv_met_Et                     lv_met_Et                     lv_met_Et                     lv_met_Et                                                       'F'    [0.0869567543268,58682.0507812]
lv_electron_Et                lv_electron_Et                lv_electron_Et                lv_electron_Et                                                  'F'    [15.0001068115,446.446594238]
lv_tau_Et                     lv_tau_Et                     lv_tau_Et                     lv_tau_Et                                                       'F'    [20.0247249603,897.134277344]
dphielectau                   dphielectau                   dphielectau                   dphielectau                                                     'F'    [0.00320380693302,3.1414437294]
dphielecmet                   dphielecmet                   dphielecmet                   dphielecmet                                                     'F'    [3.65972518921e-05,3.14153695107]
mtelecmet                     mtelecmet                     mtelecmet                     mtelecmet                                                       'F'    [0.000435188296251,3124.58056641]
electronEcalIso               electronEcalIso               electronEcalIso               electronEcalIso                                                 'F'    [0,103.247169495]
electronTrackIso              electronTrackIso              electronTrackIso              electronTrackIso                                                'F'    [0,89.6219711304]
tauTrack                      tauTrack                      tauTrack                      tauTrack                                                        'I'    [0,11]
tauLeadTrk                    tauLeadTrk                    tauLeadTrk                    tauLeadTrk                                                      'I'    [0,1]
tauECALIso                    tauECALIso                    tauECALIso                    tauECALIso                                                      'I'    [0,1]
tauElectron                   tauElectron                   tauElectron                   tauElectron                                                     'I'    [0,1]
tauCharge                     tauCharge                     tauCharge                     tauCharge                                                       'I'    [-4,4]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lv_met_Et", "lv_electron_Et", "lv_tau_Et", "dphielectau", "dphielecmet", "mtelecmet", "electronEcalIso", "electronTrackIso", "tauTrack", "tauLeadTrk", "tauECALIso", "tauElectron", "tauCharge" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.16922447652787;
   fWeightMatrix0to1[1][0] = -0.170680846484462;
   fWeightMatrix0to1[2][0] = -0.191732328274698;
   fWeightMatrix0to1[3][0] = 0.989528306803907;
   fWeightMatrix0to1[4][0] = -0.744102168668601;
   fWeightMatrix0to1[5][0] = 1.11526619015596;
   fWeightMatrix0to1[6][0] = 1.62077451404836;
   fWeightMatrix0to1[7][0] = 0.637025159174776;
   fWeightMatrix0to1[8][0] = -0.500983343606681;
   fWeightMatrix0to1[9][0] = -1.25172072047813;
   fWeightMatrix0to1[10][0] = -1.2955401570911;
   fWeightMatrix0to1[11][0] = 0.0492010296543692;
   fWeightMatrix0to1[12][0] = -0.254943928382563;
   fWeightMatrix0to1[13][0] = 0.662634764654878;
   fWeightMatrix0to1[14][0] = 0.0291373355823943;
   fWeightMatrix0to1[15][0] = 1.49750690331324;
   fWeightMatrix0to1[16][0] = 1.71564463289475;
   fWeightMatrix0to1[17][0] = -0.978653791104628;
   fWeightMatrix0to1[0][1] = 0.502352668150012;
   fWeightMatrix0to1[1][1] = 1.23869312136283;
   fWeightMatrix0to1[2][1] = 1.74862986970654;
   fWeightMatrix0to1[3][1] = -1.72925387018755;
   fWeightMatrix0to1[4][1] = -1.69319088652647;
   fWeightMatrix0to1[5][1] = -0.77732240998607;
   fWeightMatrix0to1[6][1] = 0.540095544939643;
   fWeightMatrix0to1[7][1] = -1.30035360832924;
   fWeightMatrix0to1[8][1] = -1.99698530583645;
   fWeightMatrix0to1[9][1] = -1.53147899679117;
   fWeightMatrix0to1[10][1] = 0.163325347577697;
   fWeightMatrix0to1[11][1] = 1.43448788234396;
   fWeightMatrix0to1[12][1] = -1.49348177679992;
   fWeightMatrix0to1[13][1] = 1.93966104216805;
   fWeightMatrix0to1[14][1] = -1.45930161653676;
   fWeightMatrix0to1[15][1] = -0.941872898908624;
   fWeightMatrix0to1[16][1] = 0.0143388423502404;
   fWeightMatrix0to1[17][1] = 2.34926326890386;
   fWeightMatrix0to1[0][2] = -1.69085987015364;
   fWeightMatrix0to1[1][2] = 0.506638451127785;
   fWeightMatrix0to1[2][2] = 2.6390660524154;
   fWeightMatrix0to1[3][2] = -0.815453906919636;
   fWeightMatrix0to1[4][2] = -1.97050123192161;
   fWeightMatrix0to1[5][2] = 1.9899398648888;
   fWeightMatrix0to1[6][2] = -0.999969921453411;
   fWeightMatrix0to1[7][2] = 0.268877117913392;
   fWeightMatrix0to1[8][2] = -0.0182499825679618;
   fWeightMatrix0to1[9][2] = 1.46041745878951;
   fWeightMatrix0to1[10][2] = -2.42032891269937;
   fWeightMatrix0to1[11][2] = 0.379902910968485;
   fWeightMatrix0to1[12][2] = -0.852729477088457;
   fWeightMatrix0to1[13][2] = -0.982410925145882;
   fWeightMatrix0to1[14][2] = 1.1368416710172;
   fWeightMatrix0to1[15][2] = 0.0121728838588862;
   fWeightMatrix0to1[16][2] = 0.655092725250353;
   fWeightMatrix0to1[17][2] = 2.28148152792013;
   fWeightMatrix0to1[0][3] = -1.71467566171089;
   fWeightMatrix0to1[1][3] = -0.754144639924923;
   fWeightMatrix0to1[2][3] = 0.636125385354079;
   fWeightMatrix0to1[3][3] = 1.68573866486132;
   fWeightMatrix0to1[4][3] = -0.0312685775471077;
   fWeightMatrix0to1[5][3] = 0.0986484184427458;
   fWeightMatrix0to1[6][3] = 0.904671414717342;
   fWeightMatrix0to1[7][3] = 1.39234750225418;
   fWeightMatrix0to1[8][3] = -0.948594706620376;
   fWeightMatrix0to1[9][3] = 0.992959593424029;
   fWeightMatrix0to1[10][3] = -1.37481532590232;
   fWeightMatrix0to1[11][3] = -0.750605688795142;
   fWeightMatrix0to1[12][3] = -0.224376310461589;
   fWeightMatrix0to1[13][3] = 1.19873492358045;
   fWeightMatrix0to1[14][3] = 0.0945521480810541;
   fWeightMatrix0to1[15][3] = 0.987156191690914;
   fWeightMatrix0to1[16][3] = 1.36551445434727;
   fWeightMatrix0to1[17][3] = 0.283866058361193;
   fWeightMatrix0to1[0][4] = -0.260642829562094;
   fWeightMatrix0to1[1][4] = -0.94801997709726;
   fWeightMatrix0to1[2][4] = -0.328042282727985;
   fWeightMatrix0to1[3][4] = 0.0711961781988187;
   fWeightMatrix0to1[4][4] = -0.226252691235566;
   fWeightMatrix0to1[5][4] = 0.0697717156161859;
   fWeightMatrix0to1[6][4] = 1.2177482262298;
   fWeightMatrix0to1[7][4] = 1.12191570002547;
   fWeightMatrix0to1[8][4] = -0.10241705658918;
   fWeightMatrix0to1[9][4] = 0.788476574170126;
   fWeightMatrix0to1[10][4] = 1.60920493644835;
   fWeightMatrix0to1[11][4] = 0.0417298023212726;
   fWeightMatrix0to1[12][4] = 0.417724154757812;
   fWeightMatrix0to1[13][4] = -0.774796864776524;
   fWeightMatrix0to1[14][4] = 0.266002009518734;
   fWeightMatrix0to1[15][4] = 0.149295848184195;
   fWeightMatrix0to1[16][4] = 1.65836255837936;
   fWeightMatrix0to1[17][4] = -0.385293164866332;
   fWeightMatrix0to1[0][5] = -0.251420792113311;
   fWeightMatrix0to1[1][5] = 0.0955932641557611;
   fWeightMatrix0to1[2][5] = 0.929544733584211;
   fWeightMatrix0to1[3][5] = 2.0811269618563;
   fWeightMatrix0to1[4][5] = -1.08374754567588;
   fWeightMatrix0to1[5][5] = 1.89402846186365;
   fWeightMatrix0to1[6][5] = 1.05656327461244;
   fWeightMatrix0to1[7][5] = 0.647646950490238;
   fWeightMatrix0to1[8][5] = 1.28358582672611;
   fWeightMatrix0to1[9][5] = -1.43039567294089;
   fWeightMatrix0to1[10][5] = 0.657412649595263;
   fWeightMatrix0to1[11][5] = -0.93795920291712;
   fWeightMatrix0to1[12][5] = 1.230500991671;
   fWeightMatrix0to1[13][5] = -1.64846781171045;
   fWeightMatrix0to1[14][5] = 1.01258141304426;
   fWeightMatrix0to1[15][5] = 1.01135296283861;
   fWeightMatrix0to1[16][5] = -1.26392168537097;
   fWeightMatrix0to1[17][5] = -0.839988238978573;
   fWeightMatrix0to1[0][6] = 1.78990088857441;
   fWeightMatrix0to1[1][6] = 0.72803846074268;
   fWeightMatrix0to1[2][6] = 0.879415556854967;
   fWeightMatrix0to1[3][6] = -1.16232194031126;
   fWeightMatrix0to1[4][6] = -0.214017262622202;
   fWeightMatrix0to1[5][6] = -1.13699774212215;
   fWeightMatrix0to1[6][6] = -1.70068215045113;
   fWeightMatrix0to1[7][6] = 0.0117985342386835;
   fWeightMatrix0to1[8][6] = -0.0656913597208936;
   fWeightMatrix0to1[9][6] = -0.274634872375597;
   fWeightMatrix0to1[10][6] = 0.693939305427129;
   fWeightMatrix0to1[11][6] = 1.29467462394495;
   fWeightMatrix0to1[12][6] = 0.168636813523645;
   fWeightMatrix0to1[13][6] = 0.326412086210212;
   fWeightMatrix0to1[14][6] = -0.605395670837564;
   fWeightMatrix0to1[15][6] = 0.800018682854815;
   fWeightMatrix0to1[16][6] = -0.334639479149258;
   fWeightMatrix0to1[17][6] = -1.47276112466686;
   fWeightMatrix0to1[0][7] = 0.687338736704871;
   fWeightMatrix0to1[1][7] = 1.85848638790979;
   fWeightMatrix0to1[2][7] = -1.48153549630193;
   fWeightMatrix0to1[3][7] = -1.89077955544804;
   fWeightMatrix0to1[4][7] = -1.32675057443037;
   fWeightMatrix0to1[5][7] = -1.94600124163187;
   fWeightMatrix0to1[6][7] = 0.458141952000661;
   fWeightMatrix0to1[7][7] = 0.348741932095649;
   fWeightMatrix0to1[8][7] = 0.197443973255979;
   fWeightMatrix0to1[9][7] = -0.0102126067568286;
   fWeightMatrix0to1[10][7] = 0.235614770688334;
   fWeightMatrix0to1[11][7] = 0.49669561441638;
   fWeightMatrix0to1[12][7] = -0.673071268941567;
   fWeightMatrix0to1[13][7] = -1.70727635240752;
   fWeightMatrix0to1[14][7] = -1.01086455588183;
   fWeightMatrix0to1[15][7] = 0.760978138545579;
   fWeightMatrix0to1[16][7] = -1.14903311940676;
   fWeightMatrix0to1[17][7] = -1.1985995838775;
   fWeightMatrix0to1[0][8] = 0.623194881274739;
   fWeightMatrix0to1[1][8] = 0.981494487821931;
   fWeightMatrix0to1[2][8] = 0.551749692181378;
   fWeightMatrix0to1[3][8] = 0.0734058487194368;
   fWeightMatrix0to1[4][8] = 0.965866180237304;
   fWeightMatrix0to1[5][8] = 1.43254641179524;
   fWeightMatrix0to1[6][8] = -0.99622746894623;
   fWeightMatrix0to1[7][8] = -1.15037738222595;
   fWeightMatrix0to1[8][8] = 1.47744577529725;
   fWeightMatrix0to1[9][8] = -0.264197969915229;
   fWeightMatrix0to1[10][8] = 1.42777604010746;
   fWeightMatrix0to1[11][8] = -0.492354439506221;
   fWeightMatrix0to1[12][8] = -1.13323573778185;
   fWeightMatrix0to1[13][8] = -0.126138449714922;
   fWeightMatrix0to1[14][8] = 0.900114753517312;
   fWeightMatrix0to1[15][8] = -0.939543627732418;
   fWeightMatrix0to1[16][8] = 0.0387776481352479;
   fWeightMatrix0to1[17][8] = -0.752853209437053;
   fWeightMatrix0to1[0][9] = -1.34630796086595;
   fWeightMatrix0to1[1][9] = 1.47578565234439;
   fWeightMatrix0to1[2][9] = 0.331611354604556;
   fWeightMatrix0to1[3][9] = -1.0882633228593;
   fWeightMatrix0to1[4][9] = -1.31280111089598;
   fWeightMatrix0to1[5][9] = 1.48123353092712;
   fWeightMatrix0to1[6][9] = -1.46552376992085;
   fWeightMatrix0to1[7][9] = -1.15962200054731;
   fWeightMatrix0to1[8][9] = -0.307844749368743;
   fWeightMatrix0to1[9][9] = 1.79219073984953;
   fWeightMatrix0to1[10][9] = 1.41640406197683;
   fWeightMatrix0to1[11][9] = -0.43439043315733;
   fWeightMatrix0to1[12][9] = 1.50308214689398;
   fWeightMatrix0to1[13][9] = 0.751499354030632;
   fWeightMatrix0to1[14][9] = -1.21764152069805;
   fWeightMatrix0to1[15][9] = 1.51770322855368;
   fWeightMatrix0to1[16][9] = -1.69948071477006;
   fWeightMatrix0to1[17][9] = 0.167234405778092;
   fWeightMatrix0to1[0][10] = 0.363316566411209;
   fWeightMatrix0to1[1][10] = 1.44345853402793;
   fWeightMatrix0to1[2][10] = 2.24503310741553;
   fWeightMatrix0to1[3][10] = -0.93067139477766;
   fWeightMatrix0to1[4][10] = 1.42646017716421;
   fWeightMatrix0to1[5][10] = -0.0453445928519082;
   fWeightMatrix0to1[6][10] = 2.12911057312327;
   fWeightMatrix0to1[7][10] = -2.43981477009235;
   fWeightMatrix0to1[8][10] = 0.0688216061502693;
   fWeightMatrix0to1[9][10] = 1.85764574893186;
   fWeightMatrix0to1[10][10] = -1.79185246910531;
   fWeightMatrix0to1[11][10] = 0.170369542914335;
   fWeightMatrix0to1[12][10] = -0.79387096677756;
   fWeightMatrix0to1[13][10] = 2.02148629626298;
   fWeightMatrix0to1[14][10] = -0.0204788130464186;
   fWeightMatrix0to1[15][10] = -1.58381769222465;
   fWeightMatrix0to1[16][10] = 1.23251617875647;
   fWeightMatrix0to1[17][10] = -0.57838173958143;
   fWeightMatrix0to1[0][11] = -1.04885995502305;
   fWeightMatrix0to1[1][11] = 1.78226056597935;
   fWeightMatrix0to1[2][11] = 0.0169391509367421;
   fWeightMatrix0to1[3][11] = -0.385946448703701;
   fWeightMatrix0to1[4][11] = -1.58235455038782;
   fWeightMatrix0to1[5][11] = -0.083497213884587;
   fWeightMatrix0to1[6][11] = -0.316678204169761;
   fWeightMatrix0to1[7][11] = 0.0774473038129286;
   fWeightMatrix0to1[8][11] = 0.186372907830584;
   fWeightMatrix0to1[9][11] = 0.888454655239538;
   fWeightMatrix0to1[10][11] = -1.17812309332313;
   fWeightMatrix0to1[11][11] = 0.412317037651267;
   fWeightMatrix0to1[12][11] = 1.07280038823393;
   fWeightMatrix0to1[13][11] = 0.383626196977497;
   fWeightMatrix0to1[14][11] = -0.796829482986818;
   fWeightMatrix0to1[15][11] = 1.72654156207273;
   fWeightMatrix0to1[16][11] = -1.14450267356249;
   fWeightMatrix0to1[17][11] = 0.00564162433990504;
   fWeightMatrix0to1[0][12] = -1.07760190696209;
   fWeightMatrix0to1[1][12] = 1.26687056675439;
   fWeightMatrix0to1[2][12] = -0.240181284065573;
   fWeightMatrix0to1[3][12] = -0.660102012802567;
   fWeightMatrix0to1[4][12] = 1.46067719522258;
   fWeightMatrix0to1[5][12] = 0.795371302353935;
   fWeightMatrix0to1[6][12] = 0.443272381969485;
   fWeightMatrix0to1[7][12] = 1.09804315938511;
   fWeightMatrix0to1[8][12] = -0.312695177433183;
   fWeightMatrix0to1[9][12] = 0.605760405647297;
   fWeightMatrix0to1[10][12] = -1.80291251712381;
   fWeightMatrix0to1[11][12] = 0.595339930145566;
   fWeightMatrix0to1[12][12] = 1.45859480260772;
   fWeightMatrix0to1[13][12] = -1.44930394720584;
   fWeightMatrix0to1[14][12] = -0.443578637361141;
   fWeightMatrix0to1[15][12] = -0.0421752221282615;
   fWeightMatrix0to1[16][12] = -0.53630148648374;
   fWeightMatrix0to1[17][12] = -0.716095498512363;
   fWeightMatrix0to1[0][13] = -0.905421158403004;
   fWeightMatrix0to1[1][13] = -1.044657299564;
   fWeightMatrix0to1[2][13] = 1.29492972046899;
   fWeightMatrix0to1[3][13] = -1.59085994439578;
   fWeightMatrix0to1[4][13] = 0.565102976925201;
   fWeightMatrix0to1[5][13] = 0.533643609819103;
   fWeightMatrix0to1[6][13] = 0.0330765436116146;
   fWeightMatrix0to1[7][13] = -0.210318733310989;
   fWeightMatrix0to1[8][13] = 1.95960794977787;
   fWeightMatrix0to1[9][13] = 1.32493024684197;
   fWeightMatrix0to1[10][13] = -0.208512917733456;
   fWeightMatrix0to1[11][13] = 2.15900078524393;
   fWeightMatrix0to1[12][13] = 2.21690135198486;
   fWeightMatrix0to1[13][13] = -0.502763384707394;
   fWeightMatrix0to1[14][13] = 1.75127646652883;
   fWeightMatrix0to1[15][13] = 0.178351425135642;
   fWeightMatrix0to1[16][13] = 1.629095034887;
   fWeightMatrix0to1[17][13] = -0.882720784608006;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.0317286456848239;
   fWeightMatrix1to2[0][1] = -0.104835123485686;
   fWeightMatrix1to2[0][2] = 0.268868239310933;
   fWeightMatrix1to2[0][3] = -0.132547235433586;
   fWeightMatrix1to2[0][4] = 0.616446328354694;
   fWeightMatrix1to2[0][5] = 0.0380514019653745;
   fWeightMatrix1to2[0][6] = 0.078542447079979;
   fWeightMatrix1to2[0][7] = 0.09281099176249;
   fWeightMatrix1to2[0][8] = -0.240738721680364;
   fWeightMatrix1to2[0][9] = -0.127807701702901;
   fWeightMatrix1to2[0][10] = 0.0424576333187107;
   fWeightMatrix1to2[0][11] = 0.191987230064261;
   fWeightMatrix1to2[0][12] = -0.856909741338401;
   fWeightMatrix1to2[0][13] = 0.0629953120529035;
   fWeightMatrix1to2[0][14] = 0.170943954879154;
   fWeightMatrix1to2[0][15] = 0.037138106416614;
   fWeightMatrix1to2[0][16] = -0.0948042077526408;
   fWeightMatrix1to2[0][17] = 0.125540699407633;
   fWeightMatrix1to2[0][18] = -0.222647942263401;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0.0869567543268;
   fMax_1[0][0] = 58682.0507812;
   fMin_1[1][0] = 0.0869567543268;
   fMax_1[1][0] = 58682.0507812;
   fMin_1[2][0] = 0.0869567543268;
   fMax_1[2][0] = 58682.0507812;
   fMin_1[0][1] = 15.0001068115;
   fMax_1[0][1] = 446.446594238;
   fMin_1[1][1] = 15.0001068115;
   fMax_1[1][1] = 446.446594238;
   fMin_1[2][1] = 15.0001068115;
   fMax_1[2][1] = 446.446594238;
   fMin_1[0][2] = 20.0247249603;
   fMax_1[0][2] = 897.134277344;
   fMin_1[1][2] = 20.0247249603;
   fMax_1[1][2] = 897.134277344;
   fMin_1[2][2] = 20.0247249603;
   fMax_1[2][2] = 897.134277344;
   fMin_1[0][3] = 0.00320380693302;
   fMax_1[0][3] = 3.1414437294;
   fMin_1[1][3] = 0.00320380693302;
   fMax_1[1][3] = 3.1414437294;
   fMin_1[2][3] = 0.00320380693302;
   fMax_1[2][3] = 3.1414437294;
   fMin_1[0][4] = 3.65972518921e-05;
   fMax_1[0][4] = 3.14153695107;
   fMin_1[1][4] = 3.65972518921e-05;
   fMax_1[1][4] = 3.14153695107;
   fMin_1[2][4] = 3.65972518921e-05;
   fMax_1[2][4] = 3.14153695107;
   fMin_1[0][5] = 0.000435188296251;
   fMax_1[0][5] = 3124.58056641;
   fMin_1[1][5] = 0.000435188296251;
   fMax_1[1][5] = 3124.58056641;
   fMin_1[2][5] = 0.000435188296251;
   fMax_1[2][5] = 3124.58056641;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 103.247169495;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 103.247169495;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 103.247169495;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 89.6219711304;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 89.6219711304;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 89.6219711304;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 11;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 11;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = -4;
   fMax_1[0][12] = 4;
   fMin_1[1][12] = -4;
   fMax_1[1][12] = 4;
   fMin_1[2][12] = -4;
   fMax_1[2][12] = 4;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
