// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.0.1         [262145]
ROOT Release   : 5.24/00       [333824]
Creator        : twig
Date           : Thu Dec 10 10:59:08 2009
Host           : Darwin dyn1205-245.wlan.ic.ac.uk 10.0.0 Darwin Kernel Version 10.0.0: Fri Jul 31 22:47:34 PDT 2009; root:xnu-1456.1.25~1/RELEASE_I386 i386
Dir            : /Users/twig/gbmsci/tmva
Training events: 11436
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "0.000000e+00" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
lv_met_Et                     lv_met_Et                     lv_met_Et                     lv_met_Et                                                       'F'    [0.0869567543268,58682.0507812]
lv_electron_Et                lv_electron_Et                lv_electron_Et                lv_electron_Et                                                  'F'    [15.0001068115,446.446594238]
lv_tau_Et                     lv_tau_Et                     lv_tau_Et                     lv_tau_Et                                                       'F'    [20.0247249603,897.134277344]
dphielectau                   dphielectau                   dphielectau                   dphielectau                                                     'F'    [0.00320380693302,3.14154338837]
dphielecmet                   dphielecmet                   dphielecmet                   dphielecmet                                                     'F'    [3.65972518921e-05,3.14153695107]
mtelecmet                     mtelecmet                     mtelecmet                     mtelecmet                                                       'F'    [0.000435188296251,3124.58056641]
electronEcalIso               electronEcalIso               electronEcalIso               electronEcalIso                                                 'F'    [0,103.247169495]
electronTrackIso              electronTrackIso              electronTrackIso              electronTrackIso                                                'F'    [0,89.6219711304]
tauTrack                      tauTrack                      tauTrack                      tauTrack                                                        'I'    [0,11]
tauLeadTrk                    tauLeadTrk                    tauLeadTrk                    tauLeadTrk                                                      'I'    [0,1]
tauECALIso                    tauECALIso                    tauECALIso                    tauECALIso                                                      'I'    [0,1]
tauElectron                   tauElectron                   tauElectron                   tauElectron                                                     'I'    [0,1]
tauCharge                     tauCharge                     tauCharge                     tauCharge                                                       'I'    [-4,4]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lv_met_Et", "lv_electron_Et", "lv_tau_Et", "dphielectau", "dphielecmet", "mtelecmet", "electronEcalIso", "electronTrackIso", "tauTrack", "tauLeadTrk", "tauECALIso", "tauElectron", "tauCharge" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -2.28061582716865;
   fWeightMatrix0to1[1][0] = -0.403159940143373;
   fWeightMatrix0to1[2][0] = 2.00758787517178;
   fWeightMatrix0to1[3][0] = -1.89803261486928;
   fWeightMatrix0to1[4][0] = -1.41987867814894;
   fWeightMatrix0to1[5][0] = -0.261415729953171;
   fWeightMatrix0to1[6][0] = 2.27261316139297;
   fWeightMatrix0to1[7][0] = 0.83450609613209;
   fWeightMatrix0to1[8][0] = 0.737300017772155;
   fWeightMatrix0to1[9][0] = -0.549258365662105;
   fWeightMatrix0to1[10][0] = 1.73435016437637;
   fWeightMatrix0to1[11][0] = -0.0949186553747076;
   fWeightMatrix0to1[12][0] = -1.72625341898034;
   fWeightMatrix0to1[13][0] = 1.25304766269851;
   fWeightMatrix0to1[14][0] = -0.317204490702253;
   fWeightMatrix0to1[15][0] = -1.18149584862967;
   fWeightMatrix0to1[16][0] = -0.43917504259061;
   fWeightMatrix0to1[17][0] = -0.3865016580378;
   fWeightMatrix0to1[0][1] = 0.522628453782403;
   fWeightMatrix0to1[1][1] = 1.79657539044845;
   fWeightMatrix0to1[2][1] = 0.968062159544282;
   fWeightMatrix0to1[3][1] = 1.57150375835086;
   fWeightMatrix0to1[4][1] = -1.46142670081988;
   fWeightMatrix0to1[5][1] = 1.6699588191713;
   fWeightMatrix0to1[6][1] = -1.20677602308301;
   fWeightMatrix0to1[7][1] = 0.369610008839204;
   fWeightMatrix0to1[8][1] = 0.654867638561381;
   fWeightMatrix0to1[9][1] = -2.21665772007048;
   fWeightMatrix0to1[10][1] = 0.476641919055069;
   fWeightMatrix0to1[11][1] = -0.117799312704917;
   fWeightMatrix0to1[12][1] = 2.04597987411359;
   fWeightMatrix0to1[13][1] = -1.95895081069553;
   fWeightMatrix0to1[14][1] = -1.0520061637627;
   fWeightMatrix0to1[15][1] = 2.59225348650577;
   fWeightMatrix0to1[16][1] = -0.672664210181791;
   fWeightMatrix0to1[17][1] = 1.51338955078;
   fWeightMatrix0to1[0][2] = 0.717186862495214;
   fWeightMatrix0to1[1][2] = -1.65991910554068;
   fWeightMatrix0to1[2][2] = -0.390436634376139;
   fWeightMatrix0to1[3][2] = -0.373449293192808;
   fWeightMatrix0to1[4][2] = -0.998472396889068;
   fWeightMatrix0to1[5][2] = 0.315888226201048;
   fWeightMatrix0to1[6][2] = 1.73695879113259;
   fWeightMatrix0to1[7][2] = -1.18978279900548;
   fWeightMatrix0to1[8][2] = 0.764814109789701;
   fWeightMatrix0to1[9][2] = -0.709349984312238;
   fWeightMatrix0to1[10][2] = 0.601860168750429;
   fWeightMatrix0to1[11][2] = 1.98883225586138;
   fWeightMatrix0to1[12][2] = 0.818153773303489;
   fWeightMatrix0to1[13][2] = -0.327430384291165;
   fWeightMatrix0to1[14][2] = 0.85097263208252;
   fWeightMatrix0to1[15][2] = 2.92304596280112;
   fWeightMatrix0to1[16][2] = -0.666109603782685;
   fWeightMatrix0to1[17][2] = 1.83352379324271;
   fWeightMatrix0to1[0][3] = 1.45643355215332;
   fWeightMatrix0to1[1][3] = -0.0717152886159151;
   fWeightMatrix0to1[2][3] = 1.51746919189933;
   fWeightMatrix0to1[3][3] = 0.0193009713283063;
   fWeightMatrix0to1[4][3] = -0.279924768899838;
   fWeightMatrix0to1[5][3] = 0.687733389636139;
   fWeightMatrix0to1[6][3] = 0.171436544905241;
   fWeightMatrix0to1[7][3] = -0.742575527699554;
   fWeightMatrix0to1[8][3] = 1.15197897214764;
   fWeightMatrix0to1[9][3] = 1.78099572512837;
   fWeightMatrix0to1[10][3] = -0.608185194601756;
   fWeightMatrix0to1[11][3] = 1.84003250304116;
   fWeightMatrix0to1[12][3] = -0.371324820665817;
   fWeightMatrix0to1[13][3] = 0.345829439518994;
   fWeightMatrix0to1[14][3] = 0.921205744813729;
   fWeightMatrix0to1[15][3] = 1.05931474727293;
   fWeightMatrix0to1[16][3] = 0.658921999696353;
   fWeightMatrix0to1[17][3] = -0.546083617570317;
   fWeightMatrix0to1[0][4] = -1.22292064210147;
   fWeightMatrix0to1[1][4] = 0.39844521722554;
   fWeightMatrix0to1[2][4] = -0.279429746152551;
   fWeightMatrix0to1[3][4] = -0.263657795819744;
   fWeightMatrix0to1[4][4] = -0.0334946232280333;
   fWeightMatrix0to1[5][4] = 1.58610957673234;
   fWeightMatrix0to1[6][4] = 0.182812668344977;
   fWeightMatrix0to1[7][4] = -0.0322660061279085;
   fWeightMatrix0to1[8][4] = 0.622714806244349;
   fWeightMatrix0to1[9][4] = 0.680852390830476;
   fWeightMatrix0to1[10][4] = 0.202669862048242;
   fWeightMatrix0to1[11][4] = -0.255881732989381;
   fWeightMatrix0to1[12][4] = 0.384936337470951;
   fWeightMatrix0to1[13][4] = 0.278283220527408;
   fWeightMatrix0to1[14][4] = 0.0974932198565534;
   fWeightMatrix0to1[15][4] = -0.322686153175589;
   fWeightMatrix0to1[16][4] = -0.309201558719588;
   fWeightMatrix0to1[17][4] = 0.606306845560079;
   fWeightMatrix0to1[0][5] = 0.603071449381069;
   fWeightMatrix0to1[1][5] = 0.224353480518614;
   fWeightMatrix0to1[2][5] = 0.418647697568184;
   fWeightMatrix0to1[3][5] = 0.968414866678665;
   fWeightMatrix0to1[4][5] = -0.410127462857426;
   fWeightMatrix0to1[5][5] = 1.81300263252852;
   fWeightMatrix0to1[6][5] = 0.216267818197529;
   fWeightMatrix0to1[7][5] = -1.95275036444183;
   fWeightMatrix0to1[8][5] = 0.643225589012973;
   fWeightMatrix0to1[9][5] = 0.32615464236088;
   fWeightMatrix0to1[10][5] = 0.909133276263419;
   fWeightMatrix0to1[11][5] = -1.63476085145952;
   fWeightMatrix0to1[12][5] = -0.747487477802571;
   fWeightMatrix0to1[13][5] = 1.88869722064744;
   fWeightMatrix0to1[14][5] = 1.79069620613136;
   fWeightMatrix0to1[15][5] = -0.34670101586682;
   fWeightMatrix0to1[16][5] = -0.403638173517087;
   fWeightMatrix0to1[17][5] = 2.09042303614848;
   fWeightMatrix0to1[0][6] = -2.43534689703528;
   fWeightMatrix0to1[1][6] = -1.08807864015697;
   fWeightMatrix0to1[2][6] = -1.28965981458261;
   fWeightMatrix0to1[3][6] = -0.578915016775701;
   fWeightMatrix0to1[4][6] = -0.761501013301442;
   fWeightMatrix0to1[5][6] = 0.0511602004004603;
   fWeightMatrix0to1[6][6] = -0.921485191690301;
   fWeightMatrix0to1[7][6] = -0.327925721743875;
   fWeightMatrix0to1[8][6] = 1.60555043130833;
   fWeightMatrix0to1[9][6] = 0.165648345259809;
   fWeightMatrix0to1[10][6] = 0.25393841356537;
   fWeightMatrix0to1[11][6] = 0.26590721669809;
   fWeightMatrix0to1[12][6] = -0.484805921242883;
   fWeightMatrix0to1[13][6] = -0.292134267438311;
   fWeightMatrix0to1[14][6] = -0.0584481818417554;
   fWeightMatrix0to1[15][6] = -2.11691763500843;
   fWeightMatrix0to1[16][6] = 1.42132445150862;
   fWeightMatrix0to1[17][6] = -0.74246282098377;
   fWeightMatrix0to1[0][7] = -1.21633756652255;
   fWeightMatrix0to1[1][7] = 0.315396085970929;
   fWeightMatrix0to1[2][7] = -0.585655497123558;
   fWeightMatrix0to1[3][7] = -0.870001505685551;
   fWeightMatrix0to1[4][7] = 0.151645800186625;
   fWeightMatrix0to1[5][7] = 1.65961152274461;
   fWeightMatrix0to1[6][7] = 0.0593165659883207;
   fWeightMatrix0to1[7][7] = 0.689594184683879;
   fWeightMatrix0to1[8][7] = 0.930266733587873;
   fWeightMatrix0to1[9][7] = -0.62685774252073;
   fWeightMatrix0to1[10][7] = -1.10510461475189;
   fWeightMatrix0to1[11][7] = 1.21073270889432;
   fWeightMatrix0to1[12][7] = -0.0182866532667584;
   fWeightMatrix0to1[13][7] = 0.793614852345929;
   fWeightMatrix0to1[14][7] = 0.621019447432765;
   fWeightMatrix0to1[15][7] = -2.25878781858079;
   fWeightMatrix0to1[16][7] = -1.83259135414814;
   fWeightMatrix0to1[17][7] = -0.389346217377465;
   fWeightMatrix0to1[0][8] = -0.815895537957459;
   fWeightMatrix0to1[1][8] = -1.89955123726593;
   fWeightMatrix0to1[2][8] = 1.73514545831384;
   fWeightMatrix0to1[3][8] = 1.41188730081083;
   fWeightMatrix0to1[4][8] = 0.200614491524799;
   fWeightMatrix0to1[5][8] = 1.34816836111014;
   fWeightMatrix0to1[6][8] = 0.708269442233248;
   fWeightMatrix0to1[7][8] = 1.47406525895633;
   fWeightMatrix0to1[8][8] = 0.239481791482245;
   fWeightMatrix0to1[9][8] = -1.17934037228047;
   fWeightMatrix0to1[10][8] = 0.120522277878277;
   fWeightMatrix0to1[11][8] = -1.10447945297661;
   fWeightMatrix0to1[12][8] = -0.11497861028885;
   fWeightMatrix0to1[13][8] = 0.331236552085736;
   fWeightMatrix0to1[14][8] = -0.411953896082897;
   fWeightMatrix0to1[15][8] = 1.03250092228473;
   fWeightMatrix0to1[16][8] = 1.41566678257545;
   fWeightMatrix0to1[17][8] = -0.111548878702672;
   fWeightMatrix0to1[0][9] = -1.61379104082436;
   fWeightMatrix0to1[1][9] = -0.464034929145732;
   fWeightMatrix0to1[2][9] = 0.679273332763559;
   fWeightMatrix0to1[3][9] = -0.0769302462772436;
   fWeightMatrix0to1[4][9] = -0.140945966303524;
   fWeightMatrix0to1[5][9] = -1.33865631162053;
   fWeightMatrix0to1[6][9] = -0.823084942990928;
   fWeightMatrix0to1[7][9] = -1.32635419065966;
   fWeightMatrix0to1[8][9] = 0.512935748565375;
   fWeightMatrix0to1[9][9] = 1.08929845267945;
   fWeightMatrix0to1[10][9] = -1.51838300985953;
   fWeightMatrix0to1[11][9] = -1.1238446235291;
   fWeightMatrix0to1[12][9] = 0.667142558254163;
   fWeightMatrix0to1[13][9] = 0.477578495666253;
   fWeightMatrix0to1[14][9] = -0.825311751308756;
   fWeightMatrix0to1[15][9] = -0.522228108377357;
   fWeightMatrix0to1[16][9] = -1.02690282516915;
   fWeightMatrix0to1[17][9] = -2.07426048416931;
   fWeightMatrix0to1[0][10] = -1.22718633285628;
   fWeightMatrix0to1[1][10] = -0.0313521922127031;
   fWeightMatrix0to1[2][10] = -0.285147240165285;
   fWeightMatrix0to1[3][10] = 1.91194291169327;
   fWeightMatrix0to1[4][10] = 1.09011420020927;
   fWeightMatrix0to1[5][10] = -0.300276245420887;
   fWeightMatrix0to1[6][10] = 0.0210677099735658;
   fWeightMatrix0to1[7][10] = -0.479948097593066;
   fWeightMatrix0to1[8][10] = 0.452978897802123;
   fWeightMatrix0to1[9][10] = -0.368771820527312;
   fWeightMatrix0to1[10][10] = -0.0911990169343651;
   fWeightMatrix0to1[11][10] = 1.52640881568179;
   fWeightMatrix0to1[12][10] = 1.11387299694158;
   fWeightMatrix0to1[13][10] = -0.100390994546442;
   fWeightMatrix0to1[14][10] = -0.426079826758639;
   fWeightMatrix0to1[15][10] = -0.436812461032886;
   fWeightMatrix0to1[16][10] = 0.0478877274425081;
   fWeightMatrix0to1[17][10] = -0.347858372601843;
   fWeightMatrix0to1[0][11] = 0.181479314286492;
   fWeightMatrix0to1[1][11] = 0.857217634541163;
   fWeightMatrix0to1[2][11] = -0.120838804723909;
   fWeightMatrix0to1[3][11] = -0.146791224374987;
   fWeightMatrix0to1[4][11] = 0.499588457054283;
   fWeightMatrix0to1[5][11] = -0.571648388165888;
   fWeightMatrix0to1[6][11] = 0.488744494617326;
   fWeightMatrix0to1[7][11] = 1.61451545293291;
   fWeightMatrix0to1[8][11] = 0.459395237223876;
   fWeightMatrix0to1[9][11] = -1.39991759341875;
   fWeightMatrix0to1[10][11] = 0.83037275376185;
   fWeightMatrix0to1[11][11] = -2.04153313536852;
   fWeightMatrix0to1[12][11] = -0.799067207884604;
   fWeightMatrix0to1[13][11] = -1.60385104416521;
   fWeightMatrix0to1[14][11] = 0.922285429267181;
   fWeightMatrix0to1[15][11] = 0.091795801543659;
   fWeightMatrix0to1[16][11] = 0.239692764135213;
   fWeightMatrix0to1[17][11] = 0.954723543196898;
   fWeightMatrix0to1[0][12] = -1.2882050624223;
   fWeightMatrix0to1[1][12] = -1.62551549592839;
   fWeightMatrix0to1[2][12] = -0.616861391159237;
   fWeightMatrix0to1[3][12] = 1.34193361704777;
   fWeightMatrix0to1[4][12] = -1.30421608967877;
   fWeightMatrix0to1[5][12] = 1.75545073003285;
   fWeightMatrix0to1[6][12] = -0.0636186247075954;
   fWeightMatrix0to1[7][12] = 0.586702943113527;
   fWeightMatrix0to1[8][12] = 1.71982737704384;
   fWeightMatrix0to1[9][12] = -0.58530838552693;
   fWeightMatrix0to1[10][12] = 1.61882481219161;
   fWeightMatrix0to1[11][12] = -0.65377271893229;
   fWeightMatrix0to1[12][12] = 1.42692569621713;
   fWeightMatrix0to1[13][12] = -0.894091307762285;
   fWeightMatrix0to1[14][12] = -1.28866584896031;
   fWeightMatrix0to1[15][12] = -0.361310848112926;
   fWeightMatrix0to1[16][12] = 0.373687590731557;
   fWeightMatrix0to1[17][12] = -1.27715044835157;
   fWeightMatrix0to1[0][13] = 2.6724468517361;
   fWeightMatrix0to1[1][13] = -0.241823758972259;
   fWeightMatrix0to1[2][13] = 0.351808321188919;
   fWeightMatrix0to1[3][13] = 1.70496653876911;
   fWeightMatrix0to1[4][13] = -0.458102029425099;
   fWeightMatrix0to1[5][13] = -1.78735536048043;
   fWeightMatrix0to1[6][13] = 0.935948989363751;
   fWeightMatrix0to1[7][13] = 0.471454442831125;
   fWeightMatrix0to1[8][13] = -0.953924515098458;
   fWeightMatrix0to1[9][13] = 0.987346798668929;
   fWeightMatrix0to1[10][13] = -1.38745311329628;
   fWeightMatrix0to1[11][13] = 0.419620647867017;
   fWeightMatrix0to1[12][13] = -0.286984690892215;
   fWeightMatrix0to1[13][13] = -0.756433615654312;
   fWeightMatrix0to1[14][13] = 0.959944106182511;
   fWeightMatrix0to1[15][13] = -0.381693391818874;
   fWeightMatrix0to1[16][13] = -1.12398872694198;
   fWeightMatrix0to1[17][13] = 1.47219166844696;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.02726959539024;
   fWeightMatrix1to2[0][1] = 0.086998727523695;
   fWeightMatrix1to2[0][2] = 0.0457690177913456;
   fWeightMatrix1to2[0][3] = -0.00490893910200135;
   fWeightMatrix1to2[0][4] = 0.88195697176827;
   fWeightMatrix1to2[0][5] = -1.42068158710101;
   fWeightMatrix1to2[0][6] = -0.303735595652365;
   fWeightMatrix1to2[0][7] = 0.00681384905069798;
   fWeightMatrix1to2[0][8] = -0.463846130472666;
   fWeightMatrix1to2[0][9] = -0.646133018479121;
   fWeightMatrix1to2[0][10] = 2.072509593881;
   fWeightMatrix1to2[0][11] = 0.086796963249918;
   fWeightMatrix1to2[0][12] = 0.0966379507330517;
   fWeightMatrix1to2[0][13] = -0.250220922703145;
   fWeightMatrix1to2[0][14] = -0.0618480038593914;
   fWeightMatrix1to2[0][15] = 0.246537025674122;
   fWeightMatrix1to2[0][16] = -0.202244434266762;
   fWeightMatrix1to2[0][17] = 0.155721265637062;
   fWeightMatrix1to2[0][18] = -0.268807656675193;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0.0869567543268;
   fMax_1[0][0] = 58682.0507812;
   fMin_1[1][0] = 0.0869567543268;
   fMax_1[1][0] = 58682.0507812;
   fMin_1[2][0] = 0.0869567543268;
   fMax_1[2][0] = 58682.0507812;
   fMin_1[0][1] = 15.0001068115;
   fMax_1[0][1] = 446.446594238;
   fMin_1[1][1] = 15.0001068115;
   fMax_1[1][1] = 446.446594238;
   fMin_1[2][1] = 15.0001068115;
   fMax_1[2][1] = 446.446594238;
   fMin_1[0][2] = 20.0247249603;
   fMax_1[0][2] = 897.134277344;
   fMin_1[1][2] = 20.0247249603;
   fMax_1[1][2] = 897.134277344;
   fMin_1[2][2] = 20.0247249603;
   fMax_1[2][2] = 897.134277344;
   fMin_1[0][3] = 0.00320380693302;
   fMax_1[0][3] = 3.1414437294;
   fMin_1[1][3] = 0.00320380693302;
   fMax_1[1][3] = 3.14154338837;
   fMin_1[2][3] = 0.00320380693302;
   fMax_1[2][3] = 3.14154338837;
   fMin_1[0][4] = 3.65972518921e-05;
   fMax_1[0][4] = 3.14153695107;
   fMin_1[1][4] = 3.65972518921e-05;
   fMax_1[1][4] = 3.14153695107;
   fMin_1[2][4] = 3.65972518921e-05;
   fMax_1[2][4] = 3.14153695107;
   fMin_1[0][5] = 0.000435188296251;
   fMax_1[0][5] = 3124.58056641;
   fMin_1[1][5] = 0.000435188296251;
   fMax_1[1][5] = 3124.58056641;
   fMin_1[2][5] = 0.000435188296251;
   fMax_1[2][5] = 3124.58056641;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 103.247169495;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 103.247169495;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 103.247169495;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 89.6219711304;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 89.6219711304;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 89.6219711304;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 11;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 11;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = -4;
   fMax_1[0][12] = 4;
   fMin_1[1][12] = -4;
   fMax_1[1][12] = 4;
   fMin_1[2][12] = -4;
   fMax_1[2][12] = 4;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
