// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.0.1         [262145]
ROOT Release   : 5.24/00       [333824]
Creator        : twig
Date           : Thu Dec 10 11:07:18 2009
Host           : Darwin dyn1205-245.wlan.ic.ac.uk 10.0.0 Darwin Kernel Version 10.0.0: Fri Jul 31 22:47:34 PDT 2009; root:xnu-1456.1.25~1/RELEASE_I386 i386
Dir            : /Users/twig/gbmsci/tmva
Training events: 11436
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "0.000000e+00" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
lv_met_Et                     lv_met_Et                     lv_met_Et                     lv_met_Et                                                       'F'    [0.278129458427,13037.2900391]
lv_electron_Et                lv_electron_Et                lv_electron_Et                lv_electron_Et                                                  'F'    [15.0001068115,331.976531982]
lv_tau_Et                     lv_tau_Et                     lv_tau_Et                     lv_tau_Et                                                       'F'    [20.0247249603,916.371154785]
dphielectau                   dphielectau                   dphielectau                   dphielectau                                                     'F'    [0.000231742858887,3.14145421982]
dphielecmet                   dphielecmet                   dphielecmet                   dphielecmet                                                     'F'    [3.19480895996e-05,3.14156603813]
mtelecmet                     mtelecmet                     mtelecmet                     mtelecmet                                                       'F'    [0.000971832254436,946.81036377]
electronEcalIso               electronEcalIso               electronEcalIso               electronEcalIso                                                 'F'    [0,41.4703598022]
electronTrackIso              electronTrackIso              electronTrackIso              electronTrackIso                                                'F'    [0,89.6219711304]
tauTrack                      tauTrack                      tauTrack                      tauTrack                                                        'I'    [0,11]
tauLeadTrk                    tauLeadTrk                    tauLeadTrk                    tauLeadTrk                                                      'I'    [0,1]
tauECALIso                    tauECALIso                    tauECALIso                    tauECALIso                                                      'I'    [0,1]
tauElectron                   tauElectron                   tauElectron                   tauElectron                                                     'I'    [0,1]
tauCharge                     tauCharge                     tauCharge                     tauCharge                                                       'I'    [-4,5]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lv_met_Et", "lv_electron_Et", "lv_tau_Et", "dphielectau", "dphielecmet", "mtelecmet", "electronEcalIso", "electronTrackIso", "tauTrack", "tauLeadTrk", "tauECALIso", "tauElectron", "tauCharge" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.762832455584312;
   fWeightMatrix0to1[1][0] = -0.789974478148847;
   fWeightMatrix0to1[2][0] = 0.978691143481329;
   fWeightMatrix0to1[3][0] = 0.545746914721358;
   fWeightMatrix0to1[4][0] = 0.618183090029138;
   fWeightMatrix0to1[5][0] = 2.30905028839225;
   fWeightMatrix0to1[6][0] = 0.443507604153181;
   fWeightMatrix0to1[7][0] = -0.69376041011604;
   fWeightMatrix0to1[8][0] = -1.39687394977092;
   fWeightMatrix0to1[9][0] = -2.2656586703143;
   fWeightMatrix0to1[10][0] = 2.94058595773125;
   fWeightMatrix0to1[11][0] = -3.67286587220548;
   fWeightMatrix0to1[12][0] = 0.406815829208874;
   fWeightMatrix0to1[13][0] = 0.903462412963448;
   fWeightMatrix0to1[14][0] = -1.73300477052185;
   fWeightMatrix0to1[15][0] = -0.600712013534694;
   fWeightMatrix0to1[16][0] = 1.63667942526147;
   fWeightMatrix0to1[17][0] = 0.482407665510395;
   fWeightMatrix0to1[0][1] = -0.968688040481199;
   fWeightMatrix0to1[1][1] = -1.20230067232069;
   fWeightMatrix0to1[2][1] = -3.39285937200172;
   fWeightMatrix0to1[3][1] = -0.299056139586398;
   fWeightMatrix0to1[4][1] = 0.622342218115649;
   fWeightMatrix0to1[5][1] = -0.526075280333354;
   fWeightMatrix0to1[6][1] = 3.25089037428788;
   fWeightMatrix0to1[7][1] = -1.02155084882634;
   fWeightMatrix0to1[8][1] = 0.728808161732294;
   fWeightMatrix0to1[9][1] = -1.20595669471247;
   fWeightMatrix0to1[10][1] = -4.40530304093297;
   fWeightMatrix0to1[11][1] = 0.944735306497196;
   fWeightMatrix0to1[12][1] = 4.27386341566361;
   fWeightMatrix0to1[13][1] = 0.082967389879036;
   fWeightMatrix0to1[14][1] = 2.8423547000578;
   fWeightMatrix0to1[15][1] = 0.540427979083151;
   fWeightMatrix0to1[16][1] = -0.451835263502017;
   fWeightMatrix0to1[17][1] = -1.59865906425559;
   fWeightMatrix0to1[0][2] = -1.19336661196626;
   fWeightMatrix0to1[1][2] = 2.15306118061086;
   fWeightMatrix0to1[2][2] = -0.17357402374799;
   fWeightMatrix0to1[3][2] = 1.04435564698066;
   fWeightMatrix0to1[4][2] = 0.251369283170693;
   fWeightMatrix0to1[5][2] = -2.03098580099783;
   fWeightMatrix0to1[6][2] = -0.0414077042920179;
   fWeightMatrix0to1[7][2] = 2.34253212333647;
   fWeightMatrix0to1[8][2] = -0.46659619116777;
   fWeightMatrix0to1[9][2] = 1.81407045360714;
   fWeightMatrix0to1[10][2] = -0.6132267559981;
   fWeightMatrix0to1[11][2] = -3.76981623087359;
   fWeightMatrix0to1[12][2] = -0.62328288423602;
   fWeightMatrix0to1[13][2] = -0.539344152441572;
   fWeightMatrix0to1[14][2] = -2.71498292824025;
   fWeightMatrix0to1[15][2] = -0.59199360948262;
   fWeightMatrix0to1[16][2] = -0.642370896848727;
   fWeightMatrix0to1[17][2] = -0.468176442678746;
   fWeightMatrix0to1[0][3] = 0.00347637517017261;
   fWeightMatrix0to1[1][3] = 1.05849871101109;
   fWeightMatrix0to1[2][3] = -1.17305981807781;
   fWeightMatrix0to1[3][3] = 0.208203427417672;
   fWeightMatrix0to1[4][3] = -0.119658820585669;
   fWeightMatrix0to1[5][3] = 1.35591519194461;
   fWeightMatrix0to1[6][3] = -2.68959806476343;
   fWeightMatrix0to1[7][3] = 0.362517005150244;
   fWeightMatrix0to1[8][3] = 0.422107796897211;
   fWeightMatrix0to1[9][3] = -0.947408179613159;
   fWeightMatrix0to1[10][3] = -2.9719815373582;
   fWeightMatrix0to1[11][3] = -0.549073999715907;
   fWeightMatrix0to1[12][3] = 0.486077001425201;
   fWeightMatrix0to1[13][3] = -0.0261200953341324;
   fWeightMatrix0to1[14][3] = -2.63764230410755;
   fWeightMatrix0to1[15][3] = -0.0379256017955651;
   fWeightMatrix0to1[16][3] = -2.91839268333414;
   fWeightMatrix0to1[17][3] = -2.05674461942215;
   fWeightMatrix0to1[0][4] = 0.0505832690594862;
   fWeightMatrix0to1[1][4] = 0.0375617281992431;
   fWeightMatrix0to1[2][4] = 1.13545728575313;
   fWeightMatrix0to1[3][4] = 0.649934964702814;
   fWeightMatrix0to1[4][4] = 0.940154356507529;
   fWeightMatrix0to1[5][4] = -0.712872688091128;
   fWeightMatrix0to1[6][4] = 0.426309291836234;
   fWeightMatrix0to1[7][4] = 1.17481993372696;
   fWeightMatrix0to1[8][4] = 0.341022299491762;
   fWeightMatrix0to1[9][4] = -0.263692965611658;
   fWeightMatrix0to1[10][4] = 1.24806652342397;
   fWeightMatrix0to1[11][4] = -0.448496156429465;
   fWeightMatrix0to1[12][4] = -0.271412451469548;
   fWeightMatrix0to1[13][4] = -1.10957130315693;
   fWeightMatrix0to1[14][4] = -1.19813987428257;
   fWeightMatrix0to1[15][4] = -0.15981596007085;
   fWeightMatrix0to1[16][4] = -2.77435169352749;
   fWeightMatrix0to1[17][4] = -3.69249488989957;
   fWeightMatrix0to1[0][5] = 0.0112848050057791;
   fWeightMatrix0to1[1][5] = -2.00154926460803;
   fWeightMatrix0to1[2][5] = -1.29036369207113;
   fWeightMatrix0to1[3][5] = -0.588423760005842;
   fWeightMatrix0to1[4][5] = 1.67895640019535;
   fWeightMatrix0to1[5][5] = -2.36579098913649;
   fWeightMatrix0to1[6][5] = -2.63483484503321;
   fWeightMatrix0to1[7][5] = -0.459463499565176;
   fWeightMatrix0to1[8][5] = -0.966111893463161;
   fWeightMatrix0to1[9][5] = 1.61833461042713;
   fWeightMatrix0to1[10][5] = -2.76657900890794;
   fWeightMatrix0to1[11][5] = 15.1014416039707;
   fWeightMatrix0to1[12][5] = -3.19920305965581;
   fWeightMatrix0to1[13][5] = 1.21962139077295;
   fWeightMatrix0to1[14][5] = 7.6126305307789;
   fWeightMatrix0to1[15][5] = -0.533196581292843;
   fWeightMatrix0to1[16][5] = -2.60216533832549;
   fWeightMatrix0to1[17][5] = -1.4866514619746;
   fWeightMatrix0to1[0][6] = 0.171635740188001;
   fWeightMatrix0to1[1][6] = -1.35391825526977;
   fWeightMatrix0to1[2][6] = 2.08580677271558;
   fWeightMatrix0to1[3][6] = -0.910211764107501;
   fWeightMatrix0to1[4][6] = -1.12500909656764;
   fWeightMatrix0to1[5][6] = 1.19792781007218;
   fWeightMatrix0to1[6][6] = -1.2992174520757;
   fWeightMatrix0to1[7][6] = -0.0201036534951239;
   fWeightMatrix0to1[8][6] = 1.51775148992878;
   fWeightMatrix0to1[9][6] = -0.869018199139805;
   fWeightMatrix0to1[10][6] = -1.4534140148853;
   fWeightMatrix0to1[11][6] = -0.0245598859336614;
   fWeightMatrix0to1[12][6] = -0.608089639196187;
   fWeightMatrix0to1[13][6] = 0.668242985470458;
   fWeightMatrix0to1[14][6] = -0.431375683231645;
   fWeightMatrix0to1[15][6] = 0.833165529484052;
   fWeightMatrix0to1[16][6] = 1.32894069770269;
   fWeightMatrix0to1[17][6] = -0.121438300025827;
   fWeightMatrix0to1[0][7] = 0.719847491819681;
   fWeightMatrix0to1[1][7] = 2.40263897458561;
   fWeightMatrix0to1[2][7] = 0.730295711923598;
   fWeightMatrix0to1[3][7] = -1.68388887929653;
   fWeightMatrix0to1[4][7] = 0.746391005434532;
   fWeightMatrix0to1[5][7] = -0.151660832732517;
   fWeightMatrix0to1[6][7] = -0.620820813345746;
   fWeightMatrix0to1[7][7] = 1.43128125465372;
   fWeightMatrix0to1[8][7] = -1.03549864859082;
   fWeightMatrix0to1[9][7] = -0.201080269806311;
   fWeightMatrix0to1[10][7] = -0.345524527593268;
   fWeightMatrix0to1[11][7] = -2.46609416215865;
   fWeightMatrix0to1[12][7] = -1.57720109063494;
   fWeightMatrix0to1[13][7] = 1.0093854031677;
   fWeightMatrix0to1[14][7] = -2.17682493924054;
   fWeightMatrix0to1[15][7] = -1.6377646055885;
   fWeightMatrix0to1[16][7] = -1.36790139042148;
   fWeightMatrix0to1[17][7] = 1.38478164323893;
   fWeightMatrix0to1[0][8] = 1.07246294813042;
   fWeightMatrix0to1[1][8] = 0.801148640588992;
   fWeightMatrix0to1[2][8] = 1.08840601097966;
   fWeightMatrix0to1[3][8] = 1.31950785379316;
   fWeightMatrix0to1[4][8] = -1.15851121837746;
   fWeightMatrix0to1[5][8] = -1.34311336793924;
   fWeightMatrix0to1[6][8] = 0.880538229486265;
   fWeightMatrix0to1[7][8] = 1.23261428320545;
   fWeightMatrix0to1[8][8] = 0.273453249263443;
   fWeightMatrix0to1[9][8] = 1.87813285060759;
   fWeightMatrix0to1[10][8] = 0.166599215737098;
   fWeightMatrix0to1[11][8] = 0.343202114566715;
   fWeightMatrix0to1[12][8] = 0.202331386516007;
   fWeightMatrix0to1[13][8] = 0.167961504987219;
   fWeightMatrix0to1[14][8] = 0.208509809220418;
   fWeightMatrix0to1[15][8] = 0.461687797798129;
   fWeightMatrix0to1[16][8] = 0.81929795317761;
   fWeightMatrix0to1[17][8] = -0.434090707968826;
   fWeightMatrix0to1[0][9] = -0.0409861211718592;
   fWeightMatrix0to1[1][9] = -0.251190121831119;
   fWeightMatrix0to1[2][9] = 0.473229510284895;
   fWeightMatrix0to1[3][9] = 0.839263887097831;
   fWeightMatrix0to1[4][9] = -1.77788771838627;
   fWeightMatrix0to1[5][9] = 0.352201346568355;
   fWeightMatrix0to1[6][9] = -0.421736521645258;
   fWeightMatrix0to1[7][9] = 0.0200501173280087;
   fWeightMatrix0to1[8][9] = -0.00253568471627857;
   fWeightMatrix0to1[9][9] = -0.0478043525752237;
   fWeightMatrix0to1[10][9] = -0.174075935024914;
   fWeightMatrix0to1[11][9] = -0.108602723470447;
   fWeightMatrix0to1[12][9] = -0.191111897899965;
   fWeightMatrix0to1[13][9] = -0.0374838301429277;
   fWeightMatrix0to1[14][9] = -0.161015580878866;
   fWeightMatrix0to1[15][9] = -0.0451525130374787;
   fWeightMatrix0to1[16][9] = -0.683460432982627;
   fWeightMatrix0to1[17][9] = 0.286434820643351;
   fWeightMatrix0to1[0][10] = 0.0131263467731505;
   fWeightMatrix0to1[1][10] = -0.114832561329665;
   fWeightMatrix0to1[2][10] = -0.973727847093256;
   fWeightMatrix0to1[3][10] = -0.11599142874039;
   fWeightMatrix0to1[4][10] = -2.36909971013788;
   fWeightMatrix0to1[5][10] = -1.68162784243031;
   fWeightMatrix0to1[6][10] = -0.337738174341834;
   fWeightMatrix0to1[7][10] = 0.615002388527389;
   fWeightMatrix0to1[8][10] = -0.167748043157596;
   fWeightMatrix0to1[9][10] = -0.0103358627503899;
   fWeightMatrix0to1[10][10] = -0.163513222617433;
   fWeightMatrix0to1[11][10] = -0.1163246591766;
   fWeightMatrix0to1[12][10] = -0.186363066453934;
   fWeightMatrix0to1[13][10] = 1.34284411859465;
   fWeightMatrix0to1[14][10] = -0.294633697715889;
   fWeightMatrix0to1[15][10] = -0.0160618623847745;
   fWeightMatrix0to1[16][10] = -0.223760898170222;
   fWeightMatrix0to1[17][10] = 0.164307179854542;
   fWeightMatrix0to1[0][11] = -0.0630829170425607;
   fWeightMatrix0to1[1][11] = 0.310062417214231;
   fWeightMatrix0to1[2][11] = 0.290686830573497;
   fWeightMatrix0to1[3][11] = -0.916447129420246;
   fWeightMatrix0to1[4][11] = 1.17371313324049;
   fWeightMatrix0to1[5][11] = -0.775725090488825;
   fWeightMatrix0to1[6][11] = 0.377792562463116;
   fWeightMatrix0to1[7][11] = -1.2952708209632;
   fWeightMatrix0to1[8][11] = 0.19193416664208;
   fWeightMatrix0to1[9][11] = 0.269899949847004;
   fWeightMatrix0to1[10][11] = -0.0475825987683936;
   fWeightMatrix0to1[11][11] = 0.0976534274133489;
   fWeightMatrix0to1[12][11] = 0.524446054935936;
   fWeightMatrix0to1[13][11] = -0.91028556440174;
   fWeightMatrix0to1[14][11] = 0.0263879840366993;
   fWeightMatrix0to1[15][11] = -0.103279046679049;
   fWeightMatrix0to1[16][11] = 0.3877948569221;
   fWeightMatrix0to1[17][11] = -0.0558199277135771;
   fWeightMatrix0to1[0][12] = 0.209965589110105;
   fWeightMatrix0to1[1][12] = 0.0367759246309651;
   fWeightMatrix0to1[2][12] = -0.662973987340666;
   fWeightMatrix0to1[3][12] = -0.993159771024665;
   fWeightMatrix0to1[4][12] = -0.648679358298163;
   fWeightMatrix0to1[5][12] = -0.62580763085534;
   fWeightMatrix0to1[6][12] = -0.354441024572541;
   fWeightMatrix0to1[7][12] = 0.133149640508643;
   fWeightMatrix0to1[8][12] = -0.0510409843103298;
   fWeightMatrix0to1[9][12] = -0.543848103977258;
   fWeightMatrix0to1[10][12] = 0.0887329713517331;
   fWeightMatrix0to1[11][12] = 0.211642438013671;
   fWeightMatrix0to1[12][12] = 0.215626310938388;
   fWeightMatrix0to1[13][12] = -1.53247588909237;
   fWeightMatrix0to1[14][12] = -0.154421272127474;
   fWeightMatrix0to1[15][12] = 0.208917659021484;
   fWeightMatrix0to1[16][12] = -0.394465511259106;
   fWeightMatrix0to1[17][12] = 1.50610859179082;
   fWeightMatrix0to1[0][13] = 0.456399339462716;
   fWeightMatrix0to1[1][13] = -0.317062853192396;
   fWeightMatrix0to1[2][13] = 0.106594659029354;
   fWeightMatrix0to1[3][13] = -1.73656107979317;
   fWeightMatrix0to1[4][13] = 0.434546102184572;
   fWeightMatrix0to1[5][13] = -1.75942789928965;
   fWeightMatrix0to1[6][13] = 0.319629308326645;
   fWeightMatrix0to1[7][13] = -1.88829622038267;
   fWeightMatrix0to1[8][13] = -1.94784173343027;
   fWeightMatrix0to1[9][13] = 1.40492408224087;
   fWeightMatrix0to1[10][13] = -2.36494058736085;
   fWeightMatrix0to1[11][13] = 5.50592124524469;
   fWeightMatrix0to1[12][13] = -1.45999081018299;
   fWeightMatrix0to1[13][13] = -1.65746266875207;
   fWeightMatrix0to1[14][13] = 5.51240735465889;
   fWeightMatrix0to1[15][13] = -0.929319584009777;
   fWeightMatrix0to1[16][13] = -0.528236883819254;
   fWeightMatrix0to1[17][13] = -1.35190395291455;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.150742197469121;
   fWeightMatrix1to2[0][1] = 0.353016556579538;
   fWeightMatrix1to2[0][2] = 0.235447229677323;
   fWeightMatrix1to2[0][3] = -0.141735726949439;
   fWeightMatrix1to2[0][4] = 0.174679716041807;
   fWeightMatrix1to2[0][5] = -0.210686400557031;
   fWeightMatrix1to2[0][6] = -0.295158997648353;
   fWeightMatrix1to2[0][7] = 1.54699821299503;
   fWeightMatrix1to2[0][8] = -0.0159253240202916;
   fWeightMatrix1to2[0][9] = 0.224141827499003;
   fWeightMatrix1to2[0][10] = -0.450118435451264;
   fWeightMatrix1to2[0][11] = 0.762612541103315;
   fWeightMatrix1to2[0][12] = -0.601672971598308;
   fWeightMatrix1to2[0][13] = -0.605423846857255;
   fWeightMatrix1to2[0][14] = 0.459013288104818;
   fWeightMatrix1to2[0][15] = 0.368668565598735;
   fWeightMatrix1to2[0][16] = -0.18947623121137;
   fWeightMatrix1to2[0][17] = -0.224278418652111;
   fWeightMatrix1to2[0][18] = 0.468142088637784;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0.278129458427;
   fMax_1[0][0] = 13037.2900391;
   fMin_1[1][0] = 0.278129458427;
   fMax_1[1][0] = 13037.2900391;
   fMin_1[2][0] = 0.278129458427;
   fMax_1[2][0] = 13037.2900391;
   fMin_1[0][1] = 15.0001068115;
   fMax_1[0][1] = 331.976531982;
   fMin_1[1][1] = 15.0001068115;
   fMax_1[1][1] = 331.976531982;
   fMin_1[2][1] = 15.0001068115;
   fMax_1[2][1] = 331.976531982;
   fMin_1[0][2] = 20.0247249603;
   fMax_1[0][2] = 546.432983398;
   fMin_1[1][2] = 20.0247249603;
   fMax_1[1][2] = 916.371154785;
   fMin_1[2][2] = 20.0247249603;
   fMax_1[2][2] = 916.371154785;
   fMin_1[0][3] = 0.0114453295246;
   fMax_1[0][3] = 3.1414437294;
   fMin_1[1][3] = 0.000231742858887;
   fMax_1[1][3] = 3.14145421982;
   fMin_1[2][3] = 0.000231742858887;
   fMax_1[2][3] = 3.14145421982;
   fMin_1[0][4] = 0.000271558761597;
   fMax_1[0][4] = 3.14153695107;
   fMin_1[1][4] = 3.19480895996e-05;
   fMax_1[1][4] = 3.14156603813;
   fMin_1[2][4] = 3.19480895996e-05;
   fMax_1[2][4] = 3.14156603813;
   fMin_1[0][5] = 0.00705284252763;
   fMax_1[0][5] = 946.81036377;
   fMin_1[1][5] = 0.000971832254436;
   fMax_1[1][5] = 946.81036377;
   fMin_1[2][5] = 0.000971832254436;
   fMax_1[2][5] = 946.81036377;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 41.4703598022;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 41.4703598022;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 41.4703598022;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 89.6219711304;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 89.6219711304;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 89.6219711304;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 11;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 11;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = -4;
   fMax_1[0][12] = 4;
   fMin_1[1][12] = -4;
   fMax_1[1][12] = 5;
   fMin_1[2][12] = -4;
   fMax_1[2][12] = 5;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
