// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.0.1         [262145]
ROOT Release   : 5.24/00       [333824]
Creator        : twig
Date           : Thu Dec 10 11:15:43 2009
Host           : Darwin dyn1205-245.wlan.ic.ac.uk 10.0.0 Darwin Kernel Version 10.0.0: Fri Jul 31 22:47:34 PDT 2009; root:xnu-1456.1.25~1/RELEASE_I386 i386
Dir            : /Users/twig/gbmsci/tmva
Training events: 11436
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "0.000000e+00" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
lv_met_Et                     lv_met_Et                     lv_met_Et                     lv_met_Et                                                       'F'    [0.0869567543268,58682.0507812]
lv_electron_Et                lv_electron_Et                lv_electron_Et                lv_electron_Et                                                  'F'    [15.0001068115,446.446594238]
lv_tau_Et                     lv_tau_Et                     lv_tau_Et                     lv_tau_Et                                                       'F'    [20.0247249603,897.134277344]
dphielectau                   dphielectau                   dphielectau                   dphielectau                                                     'F'    [0.00320380693302,3.1414437294]
dphielecmet                   dphielecmet                   dphielecmet                   dphielecmet                                                     'F'    [3.65972518921e-05,3.14153695107]
mtelecmet                     mtelecmet                     mtelecmet                     mtelecmet                                                       'F'    [0.000435188296251,3124.58056641]
electronEcalIso               electronEcalIso               electronEcalIso               electronEcalIso                                                 'F'    [0,103.247169495]
electronTrackIso              electronTrackIso              electronTrackIso              electronTrackIso                                                'F'    [0,89.6219711304]
tauTrack                      tauTrack                      tauTrack                      tauTrack                                                        'I'    [0,11]
tauLeadTrk                    tauLeadTrk                    tauLeadTrk                    tauLeadTrk                                                      'I'    [0,1]
tauECALIso                    tauECALIso                    tauECALIso                    tauECALIso                                                      'I'    [0,1]
tauElectron                   tauElectron                   tauElectron                   tauElectron                                                     'I'    [0,1]
tauCharge                     tauCharge                     tauCharge                     tauCharge                                                       'I'    [-4,4]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lv_met_Et", "lv_electron_Et", "lv_tau_Et", "dphielectau", "dphielecmet", "mtelecmet", "electronEcalIso", "electronTrackIso", "tauTrack", "tauLeadTrk", "tauECALIso", "tauElectron", "tauCharge" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -2.10871334338761;
   fWeightMatrix0to1[1][0] = 0.2756749025453;
   fWeightMatrix0to1[2][0] = -0.651183126696895;
   fWeightMatrix0to1[3][0] = 1.00541998362061;
   fWeightMatrix0to1[4][0] = 0.684842230623188;
   fWeightMatrix0to1[5][0] = -1.03717170605374;
   fWeightMatrix0to1[6][0] = 2.06614549430551;
   fWeightMatrix0to1[7][0] = -1.51364176433926;
   fWeightMatrix0to1[8][0] = -0.589842859083123;
   fWeightMatrix0to1[9][0] = 1.22825333146481;
   fWeightMatrix0to1[10][0] = 1.76584945516078;
   fWeightMatrix0to1[11][0] = 1.85733275384579;
   fWeightMatrix0to1[12][0] = 2.13821950516355;
   fWeightMatrix0to1[13][0] = 0.778406975448583;
   fWeightMatrix0to1[14][0] = -1.0969500663194;
   fWeightMatrix0to1[15][0] = -0.954894652566607;
   fWeightMatrix0to1[16][0] = 1.37635109204093;
   fWeightMatrix0to1[17][0] = -1.70122905281362;
   fWeightMatrix0to1[0][1] = 3.91127160739576;
   fWeightMatrix0to1[1][1] = 1.90952772858881;
   fWeightMatrix0to1[2][1] = 0.400242019219635;
   fWeightMatrix0to1[3][1] = -0.737704789782479;
   fWeightMatrix0to1[4][1] = 1.38726170556536;
   fWeightMatrix0to1[5][1] = 1.93954365945947;
   fWeightMatrix0to1[6][1] = 0.313671935092102;
   fWeightMatrix0to1[7][1] = 2.82535511944698;
   fWeightMatrix0to1[8][1] = 2.49726807526064;
   fWeightMatrix0to1[9][1] = 4.53275249038911;
   fWeightMatrix0to1[10][1] = -0.768086578203698;
   fWeightMatrix0to1[11][1] = 0.482011770141495;
   fWeightMatrix0to1[12][1] = -0.332231772032309;
   fWeightMatrix0to1[13][1] = 0.413115349716687;
   fWeightMatrix0to1[14][1] = 1.98284914195841;
   fWeightMatrix0to1[15][1] = -1.23417454150137;
   fWeightMatrix0to1[16][1] = -1.92890173454363;
   fWeightMatrix0to1[17][1] = -2.09831563575727;
   fWeightMatrix0to1[0][2] = -0.0607816886936231;
   fWeightMatrix0to1[1][2] = 1.37915065000799;
   fWeightMatrix0to1[2][2] = 2.45388082555253;
   fWeightMatrix0to1[3][2] = 0.731413703079921;
   fWeightMatrix0to1[4][2] = -0.514578475396515;
   fWeightMatrix0to1[5][2] = -1.67617486742622;
   fWeightMatrix0to1[6][2] = 0.775793658491737;
   fWeightMatrix0to1[7][2] = -1.2030568913134;
   fWeightMatrix0to1[8][2] = 1.19349378541562;
   fWeightMatrix0to1[9][2] = 1.3102429132422;
   fWeightMatrix0to1[10][2] = 1.2038213552474;
   fWeightMatrix0to1[11][2] = -1.4150333359553;
   fWeightMatrix0to1[12][2] = 0.183908278397995;
   fWeightMatrix0to1[13][2] = -0.38446907744915;
   fWeightMatrix0to1[14][2] = 0.654265835273022;
   fWeightMatrix0to1[15][2] = -1.7169512908182;
   fWeightMatrix0to1[16][2] = -2.30158644401948;
   fWeightMatrix0to1[17][2] = -0.479425798167555;
   fWeightMatrix0to1[0][3] = 0.842263997773535;
   fWeightMatrix0to1[1][3] = 0.100225600746909;
   fWeightMatrix0to1[2][3] = -0.886921504155567;
   fWeightMatrix0to1[3][3] = -1.24915658532103;
   fWeightMatrix0to1[4][3] = -2.29371690051612;
   fWeightMatrix0to1[5][3] = 0.723829923417119;
   fWeightMatrix0to1[6][3] = -1.8429625309424;
   fWeightMatrix0to1[7][3] = -0.620600166134018;
   fWeightMatrix0to1[8][3] = -1.18120552637732;
   fWeightMatrix0to1[9][3] = -0.380337781197768;
   fWeightMatrix0to1[10][3] = -1.98372513854249;
   fWeightMatrix0to1[11][3] = 0.749934572547029;
   fWeightMatrix0to1[12][3] = 1.70562277198856;
   fWeightMatrix0to1[13][3] = 2.07743965683769;
   fWeightMatrix0to1[14][3] = 0.289350986422209;
   fWeightMatrix0to1[15][3] = 0.05326291115135;
   fWeightMatrix0to1[16][3] = 1.66703783654219;
   fWeightMatrix0to1[17][3] = -0.0876303344044532;
   fWeightMatrix0to1[0][4] = 0.29534398888421;
   fWeightMatrix0to1[1][4] = -0.218865573629362;
   fWeightMatrix0to1[2][4] = 2.22705791513012;
   fWeightMatrix0to1[3][4] = -1.22853404934933;
   fWeightMatrix0to1[4][4] = -0.599330514155571;
   fWeightMatrix0to1[5][4] = -1.26261392707465;
   fWeightMatrix0to1[6][4] = 2.08074252000087;
   fWeightMatrix0to1[7][4] = -2.42039649614615;
   fWeightMatrix0to1[8][4] = -0.512152642771878;
   fWeightMatrix0to1[9][4] = 0.16279060473563;
   fWeightMatrix0to1[10][4] = 0.220635721078737;
   fWeightMatrix0to1[11][4] = 0.499381951690731;
   fWeightMatrix0to1[12][4] = 1.51972918478254;
   fWeightMatrix0to1[13][4] = 1.9898108475441;
   fWeightMatrix0to1[14][4] = -0.657572756840221;
   fWeightMatrix0to1[15][4] = -0.580938498372128;
   fWeightMatrix0to1[16][4] = -1.73451813628587;
   fWeightMatrix0to1[17][4] = -2.07490148023765;
   fWeightMatrix0to1[0][5] = -1.13829066002857;
   fWeightMatrix0to1[1][5] = 0.804957101714041;
   fWeightMatrix0to1[2][5] = 0.867305966468517;
   fWeightMatrix0to1[3][5] = -2.14525868245823;
   fWeightMatrix0to1[4][5] = -1.57095939762134;
   fWeightMatrix0to1[5][5] = 1.57020096677803;
   fWeightMatrix0to1[6][5] = -0.479488425307702;
   fWeightMatrix0to1[7][5] = 0.194743511422182;
   fWeightMatrix0to1[8][5] = 0.667352794812931;
   fWeightMatrix0to1[9][5] = -0.373476813263939;
   fWeightMatrix0to1[10][5] = -0.225087456156418;
   fWeightMatrix0to1[11][5] = 1.20677631810195;
   fWeightMatrix0to1[12][5] = -1.31456024784273;
   fWeightMatrix0to1[13][5] = 1.25205127640648;
   fWeightMatrix0to1[14][5] = -0.097088095149564;
   fWeightMatrix0to1[15][5] = 0.161276583173707;
   fWeightMatrix0to1[16][5] = -0.156028903813079;
   fWeightMatrix0to1[17][5] = 0.210179571510007;
   fWeightMatrix0to1[0][6] = 0.146440470449331;
   fWeightMatrix0to1[1][6] = -0.496985288949427;
   fWeightMatrix0to1[2][6] = 0.383674599138315;
   fWeightMatrix0to1[3][6] = -0.292472210324199;
   fWeightMatrix0to1[4][6] = -0.714064165432876;
   fWeightMatrix0to1[5][6] = -1.74744208089321;
   fWeightMatrix0to1[6][6] = -0.731962569798551;
   fWeightMatrix0to1[7][6] = 0.310591363196243;
   fWeightMatrix0to1[8][6] = -0.224995958137512;
   fWeightMatrix0to1[9][6] = 0.208653130984013;
   fWeightMatrix0to1[10][6] = 1.35027037064456;
   fWeightMatrix0to1[11][6] = 0.123418112905045;
   fWeightMatrix0to1[12][6] = 0.249939562611236;
   fWeightMatrix0to1[13][6] = -0.120936740803691;
   fWeightMatrix0to1[14][6] = 0.658399600290824;
   fWeightMatrix0to1[15][6] = -0.78066756859441;
   fWeightMatrix0to1[16][6] = 1.19180810098682;
   fWeightMatrix0to1[17][6] = -0.644227223997458;
   fWeightMatrix0to1[0][7] = 1.68270956952652;
   fWeightMatrix0to1[1][7] = 1.52355711542658;
   fWeightMatrix0to1[2][7] = -0.339530156317151;
   fWeightMatrix0to1[3][7] = 1.31857879722291;
   fWeightMatrix0to1[4][7] = 1.25718623006524;
   fWeightMatrix0to1[5][7] = -1.06485745564784;
   fWeightMatrix0to1[6][7] = -0.422631788571109;
   fWeightMatrix0to1[7][7] = 0.151548362677762;
   fWeightMatrix0to1[8][7] = -0.40236069778515;
   fWeightMatrix0to1[9][7] = -0.550990553405615;
   fWeightMatrix0to1[10][7] = 0.4344137252814;
   fWeightMatrix0to1[11][7] = -0.137104882484942;
   fWeightMatrix0to1[12][7] = -0.349191605664245;
   fWeightMatrix0to1[13][7] = 1.77458543491017;
   fWeightMatrix0to1[14][7] = -1.40907347283043;
   fWeightMatrix0to1[15][7] = 1.11718984270832;
   fWeightMatrix0to1[16][7] = -0.202225879433307;
   fWeightMatrix0to1[17][7] = 0.99888342906859;
   fWeightMatrix0to1[0][8] = 0.332255602083843;
   fWeightMatrix0to1[1][8] = -0.727562714708742;
   fWeightMatrix0to1[2][8] = 0.369807532898787;
   fWeightMatrix0to1[3][8] = -1.17885723407735;
   fWeightMatrix0to1[4][8] = -0.621081858793909;
   fWeightMatrix0to1[5][8] = -0.383546024920557;
   fWeightMatrix0to1[6][8] = -0.673341455067183;
   fWeightMatrix0to1[7][8] = 0.430225596903379;
   fWeightMatrix0to1[8][8] = -0.639404075490306;
   fWeightMatrix0to1[9][8] = -3.20833070579623;
   fWeightMatrix0to1[10][8] = 0.373791332337068;
   fWeightMatrix0to1[11][8] = 0.26325372436895;
   fWeightMatrix0to1[12][8] = 0.604232322205756;
   fWeightMatrix0to1[13][8] = 0.581364739570818;
   fWeightMatrix0to1[14][8] = 0.044924952078743;
   fWeightMatrix0to1[15][8] = 0.0809544759433479;
   fWeightMatrix0to1[16][8] = -1.15342594776386;
   fWeightMatrix0to1[17][8] = 0.735348167163291;
   fWeightMatrix0to1[0][9] = 0.226254689957102;
   fWeightMatrix0to1[1][9] = -0.791545253269023;
   fWeightMatrix0to1[2][9] = -0.233711921638233;
   fWeightMatrix0to1[3][9] = -0.0623864704924559;
   fWeightMatrix0to1[4][9] = -1.21534891957967;
   fWeightMatrix0to1[5][9] = 0.612122888495847;
   fWeightMatrix0to1[6][9] = 0.196537990368288;
   fWeightMatrix0to1[7][9] = 2.69170161670526;
   fWeightMatrix0to1[8][9] = 0.231012595693055;
   fWeightMatrix0to1[9][9] = 0.720456180932814;
   fWeightMatrix0to1[10][9] = -0.454108983661331;
   fWeightMatrix0to1[11][9] = 1.73503711197032;
   fWeightMatrix0to1[12][9] = -0.172347875506138;
   fWeightMatrix0to1[13][9] = 0.601942830286914;
   fWeightMatrix0to1[14][9] = -0.850888936326535;
   fWeightMatrix0to1[15][9] = 1.29911417752246;
   fWeightMatrix0to1[16][9] = 0.190372249440392;
   fWeightMatrix0to1[17][9] = 2.40739015458107;
   fWeightMatrix0to1[0][10] = -0.17015230637743;
   fWeightMatrix0to1[1][10] = -0.620071781453847;
   fWeightMatrix0to1[2][10] = 1.04842124048937;
   fWeightMatrix0to1[3][10] = 1.09235402612834;
   fWeightMatrix0to1[4][10] = 1.17662874483987;
   fWeightMatrix0to1[5][10] = -0.649700743209889;
   fWeightMatrix0to1[6][10] = 0.418628078346475;
   fWeightMatrix0to1[7][10] = -0.377499677317097;
   fWeightMatrix0to1[8][10] = 0.129303775943682;
   fWeightMatrix0to1[9][10] = 0.176222025386128;
   fWeightMatrix0to1[10][10] = 0.327152432409908;
   fWeightMatrix0to1[11][10] = 1.59814172984858;
   fWeightMatrix0to1[12][10] = 0.198692203157127;
   fWeightMatrix0to1[13][10] = -0.813221915189005;
   fWeightMatrix0to1[14][10] = 0.548331341502182;
   fWeightMatrix0to1[15][10] = -0.590802691062655;
   fWeightMatrix0to1[16][10] = 1.14614443176811;
   fWeightMatrix0to1[17][10] = -0.492277072980328;
   fWeightMatrix0to1[0][11] = -0.252729184077389;
   fWeightMatrix0to1[1][11] = -1.07341314505831;
   fWeightMatrix0to1[2][11] = -2.12761823584401;
   fWeightMatrix0to1[3][11] = 0.834464236627208;
   fWeightMatrix0to1[4][11] = 0.199329068281613;
   fWeightMatrix0to1[5][11] = 0.515187195055667;
   fWeightMatrix0to1[6][11] = -1.80856394512109;
   fWeightMatrix0to1[7][11] = 2.07729678668;
   fWeightMatrix0to1[8][11] = -1.11272429846353;
   fWeightMatrix0to1[9][11] = -2.51891871717032;
   fWeightMatrix0to1[10][11] = -1.83330337791368;
   fWeightMatrix0to1[11][11] = 0.0985901776610328;
   fWeightMatrix0to1[12][11] = -0.229992182400268;
   fWeightMatrix0to1[13][11] = -1.46837624790106;
   fWeightMatrix0to1[14][11] = -0.549152989520224;
   fWeightMatrix0to1[15][11] = 1.81826179505644;
   fWeightMatrix0to1[16][11] = 0.854877502887624;
   fWeightMatrix0to1[17][11] = 1.98284080839391;
   fWeightMatrix0to1[0][12] = 0.225439511835711;
   fWeightMatrix0to1[1][12] = 1.17646691073347;
   fWeightMatrix0to1[2][12] = -1.34951360939994;
   fWeightMatrix0to1[3][12] = 1.30772323838534;
   fWeightMatrix0to1[4][12] = -0.401603962095549;
   fWeightMatrix0to1[5][12] = 0.0018876325936963;
   fWeightMatrix0to1[6][12] = -0.890786004867596;
   fWeightMatrix0to1[7][12] = -0.617849593617297;
   fWeightMatrix0to1[8][12] = -0.958172202357273;
   fWeightMatrix0to1[9][12] = -0.302544915795019;
   fWeightMatrix0to1[10][12] = 0.914512489717081;
   fWeightMatrix0to1[11][12] = -0.292394977470081;
   fWeightMatrix0to1[12][12] = 0.636291389433018;
   fWeightMatrix0to1[13][12] = -1.01248132389735;
   fWeightMatrix0to1[14][12] = -0.060442141142633;
   fWeightMatrix0to1[15][12] = -1.37626928729372;
   fWeightMatrix0to1[16][12] = -1.9837706776336;
   fWeightMatrix0to1[17][12] = -1.08882633341542;
   fWeightMatrix0to1[0][13] = 0.738316570188998;
   fWeightMatrix0to1[1][13] = -0.8488600776808;
   fWeightMatrix0to1[2][13] = 0.473084142122931;
   fWeightMatrix0to1[3][13] = 1.7853736069233;
   fWeightMatrix0to1[4][13] = 2.31987419519483;
   fWeightMatrix0to1[5][13] = -1.60276081344001;
   fWeightMatrix0to1[6][13] = -2.27675772470195;
   fWeightMatrix0to1[7][13] = 2.31991155263636;
   fWeightMatrix0to1[8][13] = 0.0455544635414446;
   fWeightMatrix0to1[9][13] = -0.261877050140525;
   fWeightMatrix0to1[10][13] = 0.853954167956237;
   fWeightMatrix0to1[11][13] = -1.04737662030715;
   fWeightMatrix0to1[12][13] = 0.120672522449613;
   fWeightMatrix0to1[13][13] = 0.263960259636333;
   fWeightMatrix0to1[14][13] = 0.430956038777321;
   fWeightMatrix0to1[15][13] = 2.08716111855967;
   fWeightMatrix0to1[16][13] = 0.107185907858074;
   fWeightMatrix0to1[17][13] = -2.12033968154108;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.270034388989185;
   fWeightMatrix1to2[0][1] = 1.54644937589491;
   fWeightMatrix1to2[0][2] = 0.245981139082226;
   fWeightMatrix1to2[0][3] = -0.413471064717004;
   fWeightMatrix1to2[0][4] = 0.118590827572969;
   fWeightMatrix1to2[0][5] = 0.0367003656738422;
   fWeightMatrix1to2[0][6] = -0.476046007311195;
   fWeightMatrix1to2[0][7] = 0.596951237437218;
   fWeightMatrix1to2[0][8] = -1.11175892798916;
   fWeightMatrix1to2[0][9] = 0.898535636100728;
   fWeightMatrix1to2[0][10] = 0.592644934826474;
   fWeightMatrix1to2[0][11] = -0.060761155281828;
   fWeightMatrix1to2[0][12] = 0.0294271943933752;
   fWeightMatrix1to2[0][13] = -0.436233477949869;
   fWeightMatrix1to2[0][14] = -0.0987089295863543;
   fWeightMatrix1to2[0][15] = 0.782545974158514;
   fWeightMatrix1to2[0][16] = 0.142799703880348;
   fWeightMatrix1to2[0][17] = -0.588951826853815;
   fWeightMatrix1to2[0][18] = -0.10484113266005;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0.0869567543268;
   fMax_1[0][0] = 58682.0507812;
   fMin_1[1][0] = 0.0869567543268;
   fMax_1[1][0] = 58682.0507812;
   fMin_1[2][0] = 0.0869567543268;
   fMax_1[2][0] = 58682.0507812;
   fMin_1[0][1] = 15.0001068115;
   fMax_1[0][1] = 446.446594238;
   fMin_1[1][1] = 15.0001068115;
   fMax_1[1][1] = 446.446594238;
   fMin_1[2][1] = 15.0001068115;
   fMax_1[2][1] = 446.446594238;
   fMin_1[0][2] = 20.0247249603;
   fMax_1[0][2] = 897.134277344;
   fMin_1[1][2] = 20.0247249603;
   fMax_1[1][2] = 897.134277344;
   fMin_1[2][2] = 20.0247249603;
   fMax_1[2][2] = 897.134277344;
   fMin_1[0][3] = 0.00320380693302;
   fMax_1[0][3] = 3.1414437294;
   fMin_1[1][3] = 0.00320380693302;
   fMax_1[1][3] = 3.1414437294;
   fMin_1[2][3] = 0.00320380693302;
   fMax_1[2][3] = 3.1414437294;
   fMin_1[0][4] = 3.65972518921e-05;
   fMax_1[0][4] = 3.14153695107;
   fMin_1[1][4] = 3.65972518921e-05;
   fMax_1[1][4] = 3.14153695107;
   fMin_1[2][4] = 3.65972518921e-05;
   fMax_1[2][4] = 3.14153695107;
   fMin_1[0][5] = 0.000435188296251;
   fMax_1[0][5] = 3124.58056641;
   fMin_1[1][5] = 0.000435188296251;
   fMax_1[1][5] = 3124.58056641;
   fMin_1[2][5] = 0.000435188296251;
   fMax_1[2][5] = 3124.58056641;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 103.247169495;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 103.247169495;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 103.247169495;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 89.6219711304;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 89.6219711304;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 89.6219711304;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 11;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 11;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = -4;
   fMax_1[0][12] = 4;
   fMin_1[1][12] = -4;
   fMax_1[1][12] = 4;
   fMin_1[2][12] = -4;
   fMax_1[2][12] = 4;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
