// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.0.1         [262145]
ROOT Release   : 5.24/00       [333824]
Creator        : twig
Date           : Thu Dec 10 11:21:43 2009
Host           : Darwin dyn1205-245.wlan.ic.ac.uk 10.0.0 Darwin Kernel Version 10.0.0: Fri Jul 31 22:47:34 PDT 2009; root:xnu-1456.1.25~1/RELEASE_I386 i386
Dir            : /Users/twig/gbmsci/tmva
Training events: 11436
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "0.000000e+00" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
lv_met_Et                     lv_met_Et                     lv_met_Et                     lv_met_Et                                                       'F'    [0.0869567543268,58682.0507812]
lv_electron_Et                lv_electron_Et                lv_electron_Et                lv_electron_Et                                                  'F'    [15.0001068115,446.446594238]
lv_tau_Et                     lv_tau_Et                     lv_tau_Et                     lv_tau_Et                                                       'F'    [20.0247249603,923.271057129]
dphielectau                   dphielectau                   dphielectau                   dphielectau                                                     'F'    [0.00320380693302,3.14152598381]
dphielecmet                   dphielecmet                   dphielecmet                   dphielecmet                                                     'F'    [3.65972518921e-05,3.14153695107]
mtelecmet                     mtelecmet                     mtelecmet                     mtelecmet                                                       'F'    [0.000435188296251,3124.58056641]
electronEcalIso               electronEcalIso               electronEcalIso               electronEcalIso                                                 'F'    [0,103.247169495]
electronTrackIso              electronTrackIso              electronTrackIso              electronTrackIso                                                'F'    [0,89.6219711304]
tauTrack                      tauTrack                      tauTrack                      tauTrack                                                        'I'    [0,11]
tauLeadTrk                    tauLeadTrk                    tauLeadTrk                    tauLeadTrk                                                      'I'    [0,1]
tauECALIso                    tauECALIso                    tauECALIso                    tauECALIso                                                      'I'    [0,1]
tauElectron                   tauElectron                   tauElectron                   tauElectron                                                     'I'    [0,1]
tauCharge                     tauCharge                     tauCharge                     tauCharge                                                       'I'    [-4,4]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lv_met_Et", "lv_electron_Et", "lv_tau_Et", "dphielectau", "dphielecmet", "mtelecmet", "electronEcalIso", "electronTrackIso", "tauTrack", "tauLeadTrk", "tauECALIso", "tauElectron", "tauCharge" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.533394340816545;
   fWeightMatrix0to1[1][0] = -1.98781158949519;
   fWeightMatrix0to1[2][0] = 0.868648365300627;
   fWeightMatrix0to1[3][0] = -0.787697441260774;
   fWeightMatrix0to1[4][0] = -0.344239915646087;
   fWeightMatrix0to1[5][0] = -3.81785657606779;
   fWeightMatrix0to1[6][0] = -1.3932353896584;
   fWeightMatrix0to1[7][0] = 1.05246165138923;
   fWeightMatrix0to1[8][0] = -0.447739919190407;
   fWeightMatrix0to1[9][0] = -1.98342668480136;
   fWeightMatrix0to1[10][0] = -1.75544465300439;
   fWeightMatrix0to1[11][0] = 0.0482198511667317;
   fWeightMatrix0to1[12][0] = 1.43731796530989;
   fWeightMatrix0to1[13][0] = -1.7485425685045;
   fWeightMatrix0to1[14][0] = 0.539781083968752;
   fWeightMatrix0to1[15][0] = -0.60605355369394;
   fWeightMatrix0to1[16][0] = 0.749122612093518;
   fWeightMatrix0to1[17][0] = 0.19933448802048;
   fWeightMatrix0to1[0][1] = -1.12201603278542;
   fWeightMatrix0to1[1][1] = 0.764328951423991;
   fWeightMatrix0to1[2][1] = 1.24100458614658;
   fWeightMatrix0to1[3][1] = -2.90942835257665;
   fWeightMatrix0to1[4][1] = 2.29025803380017;
   fWeightMatrix0to1[5][1] = 3.92930130101453;
   fWeightMatrix0to1[6][1] = -1.00570418579048;
   fWeightMatrix0to1[7][1] = -2.55586640692981;
   fWeightMatrix0to1[8][1] = 0.594720403177751;
   fWeightMatrix0to1[9][1] = 1.03055466887856;
   fWeightMatrix0to1[10][1] = 0.804984135429385;
   fWeightMatrix0to1[11][1] = -0.280383405847142;
   fWeightMatrix0to1[12][1] = -1.63797196950662;
   fWeightMatrix0to1[13][1] = 0.626426601849088;
   fWeightMatrix0to1[14][1] = 1.11446894605416;
   fWeightMatrix0to1[15][1] = -2.43018216351326;
   fWeightMatrix0to1[16][1] = 1.17620626805848;
   fWeightMatrix0to1[17][1] = 0.695393498509745;
   fWeightMatrix0to1[0][2] = 1.64234478210567;
   fWeightMatrix0to1[1][2] = 2.30591624416572;
   fWeightMatrix0to1[2][2] = 2.90709063662994;
   fWeightMatrix0to1[3][2] = -0.87063454474444;
   fWeightMatrix0to1[4][2] = -0.121267095959763;
   fWeightMatrix0to1[5][2] = 0.951844807225198;
   fWeightMatrix0to1[6][2] = -0.459052403995146;
   fWeightMatrix0to1[7][2] = 0.38310180272302;
   fWeightMatrix0to1[8][2] = -0.266898755996031;
   fWeightMatrix0to1[9][2] = -0.194668138877371;
   fWeightMatrix0to1[10][2] = -1.01494877318483;
   fWeightMatrix0to1[11][2] = -1.99647789552785;
   fWeightMatrix0to1[12][2] = -1.44356397874678;
   fWeightMatrix0to1[13][2] = -0.900622554767528;
   fWeightMatrix0to1[14][2] = -1.06973989296912;
   fWeightMatrix0to1[15][2] = 1.16881987297645;
   fWeightMatrix0to1[16][2] = -1.30708404352529;
   fWeightMatrix0to1[17][2] = -1.13753833377396;
   fWeightMatrix0to1[0][3] = 1.64210560040201;
   fWeightMatrix0to1[1][3] = -1.61067366419307;
   fWeightMatrix0to1[2][3] = 0.258390952519276;
   fWeightMatrix0to1[3][3] = 0.250727502188518;
   fWeightMatrix0to1[4][3] = 0.0941781783094073;
   fWeightMatrix0to1[5][3] = -1.90699200624391;
   fWeightMatrix0to1[6][3] = 1.26918942137584;
   fWeightMatrix0to1[7][3] = -1.41687376746038;
   fWeightMatrix0to1[8][3] = -0.482804502764969;
   fWeightMatrix0to1[9][3] = -0.219418110377941;
   fWeightMatrix0to1[10][3] = 1.65222694967845;
   fWeightMatrix0to1[11][3] = -0.335087986413275;
   fWeightMatrix0to1[12][3] = -1.78630567857651;
   fWeightMatrix0to1[13][3] = 0.0909084418911653;
   fWeightMatrix0to1[14][3] = -1.65804300702971;
   fWeightMatrix0to1[15][3] = 0.726641784085694;
   fWeightMatrix0to1[16][3] = 0.989888218354138;
   fWeightMatrix0to1[17][3] = 0.394874551913549;
   fWeightMatrix0to1[0][4] = -0.858073274679776;
   fWeightMatrix0to1[1][4] = -0.136122790745321;
   fWeightMatrix0to1[2][4] = 1.13998622858564;
   fWeightMatrix0to1[3][4] = -2.63869061790348;
   fWeightMatrix0to1[4][4] = 1.48017782038802;
   fWeightMatrix0to1[5][4] = -1.00323510104107;
   fWeightMatrix0to1[6][4] = -0.166306092773444;
   fWeightMatrix0to1[7][4] = -0.529796373621837;
   fWeightMatrix0to1[8][4] = 0.786694906521858;
   fWeightMatrix0to1[9][4] = -0.621159990194549;
   fWeightMatrix0to1[10][4] = -0.724189900191664;
   fWeightMatrix0to1[11][4] = 1.42059584225477;
   fWeightMatrix0to1[12][4] = -0.190353999009958;
   fWeightMatrix0to1[13][4] = -2.34650308609866;
   fWeightMatrix0to1[14][4] = 1.61783348263767;
   fWeightMatrix0to1[15][4] = 0.00300399895627068;
   fWeightMatrix0to1[16][4] = 1.43595112489912;
   fWeightMatrix0to1[17][4] = -2.20600654620096;
   fWeightMatrix0to1[0][5] = 1.57651844224299;
   fWeightMatrix0to1[1][5] = -0.9997997023866;
   fWeightMatrix0to1[2][5] = -0.541774513280386;
   fWeightMatrix0to1[3][5] = 1.26996692974346;
   fWeightMatrix0to1[4][5] = 1.41256397271748;
   fWeightMatrix0to1[5][5] = -3.05269853546958;
   fWeightMatrix0to1[6][5] = -1.08553125709004;
   fWeightMatrix0to1[7][5] = -0.476404070641485;
   fWeightMatrix0to1[8][5] = 1.60635616075856;
   fWeightMatrix0to1[9][5] = 0.301603188361799;
   fWeightMatrix0to1[10][5] = -0.793237620588592;
   fWeightMatrix0to1[11][5] = 1.17215294647325;
   fWeightMatrix0to1[12][5] = 1.1492430673984;
   fWeightMatrix0to1[13][5] = -1.41228536017765;
   fWeightMatrix0to1[14][5] = 1.01035852067901;
   fWeightMatrix0to1[15][5] = 0.400087827005631;
   fWeightMatrix0to1[16][5] = 0.757483682816882;
   fWeightMatrix0to1[17][5] = -0.543263747031484;
   fWeightMatrix0to1[0][6] = 1.80280954627394;
   fWeightMatrix0to1[1][6] = -0.0241630275828717;
   fWeightMatrix0to1[2][6] = -1.2497553476279;
   fWeightMatrix0to1[3][6] = 1.53347754498001;
   fWeightMatrix0to1[4][6] = 0.125566851288303;
   fWeightMatrix0to1[5][6] = 0.450480295559796;
   fWeightMatrix0to1[6][6] = -2.16155407206365;
   fWeightMatrix0to1[7][6] = 1.83916842128269;
   fWeightMatrix0to1[8][6] = -1.35717150053546;
   fWeightMatrix0to1[9][6] = 0.858603317048951;
   fWeightMatrix0to1[10][6] = -0.186276704276976;
   fWeightMatrix0to1[11][6] = 0.397035908410514;
   fWeightMatrix0to1[12][6] = 0.430449739667934;
   fWeightMatrix0to1[13][6] = -0.328589371430882;
   fWeightMatrix0to1[14][6] = 0.862513860932374;
   fWeightMatrix0to1[15][6] = 0.0682858563071055;
   fWeightMatrix0to1[16][6] = -0.237115446606808;
   fWeightMatrix0to1[17][6] = -0.958409972243631;
   fWeightMatrix0to1[0][7] = 1.59855784914166;
   fWeightMatrix0to1[1][7] = -1.06573012798903;
   fWeightMatrix0to1[2][7] = 1.85539105466755;
   fWeightMatrix0to1[3][7] = 0.194848828756168;
   fWeightMatrix0to1[4][7] = -0.53329232680335;
   fWeightMatrix0to1[5][7] = -0.774019830357036;
   fWeightMatrix0to1[6][7] = 1.29615916066942;
   fWeightMatrix0to1[7][7] = 1.00005043650102;
   fWeightMatrix0to1[8][7] = 1.27063489388116;
   fWeightMatrix0to1[9][7] = -0.121116743011168;
   fWeightMatrix0to1[10][7] = -1.85050418006832;
   fWeightMatrix0to1[11][7] = 1.51798306747813;
   fWeightMatrix0to1[12][7] = 0.0293288195172729;
   fWeightMatrix0to1[13][7] = 1.06147442194317;
   fWeightMatrix0to1[14][7] = 0.77475228139399;
   fWeightMatrix0to1[15][7] = -0.00090403805063943;
   fWeightMatrix0to1[16][7] = 0.314143849924348;
   fWeightMatrix0to1[17][7] = -1.69059375573334;
   fWeightMatrix0to1[0][8] = 1.45662786981501;
   fWeightMatrix0to1[1][8] = -1.6379314620948;
   fWeightMatrix0to1[2][8] = -2.30466104926628;
   fWeightMatrix0to1[3][8] = -0.784144208866075;
   fWeightMatrix0to1[4][8] = -2.10779717159261;
   fWeightMatrix0to1[5][8] = -0.236876203166741;
   fWeightMatrix0to1[6][8] = -1.07336460977958;
   fWeightMatrix0to1[7][8] = 1.2409522786052;
   fWeightMatrix0to1[8][8] = -0.914039868912837;
   fWeightMatrix0to1[9][8] = -1.23400618128203;
   fWeightMatrix0to1[10][8] = -1.64387506096547;
   fWeightMatrix0to1[11][8] = 0.835467187774455;
   fWeightMatrix0to1[12][8] = 0.380410809462737;
   fWeightMatrix0to1[13][8] = 0.367974641387316;
   fWeightMatrix0to1[14][8] = 0.0193038656557881;
   fWeightMatrix0to1[15][8] = -0.467451711097353;
   fWeightMatrix0to1[16][8] = 2.02647953090012;
   fWeightMatrix0to1[17][8] = 0.99819130304156;
   fWeightMatrix0to1[0][9] = 1.4376693430778;
   fWeightMatrix0to1[1][9] = -0.117280681629252;
   fWeightMatrix0to1[2][9] = 0.782269908377911;
   fWeightMatrix0to1[3][9] = 1.92958419347032;
   fWeightMatrix0to1[4][9] = -1.93597840218666;
   fWeightMatrix0to1[5][9] = -0.351732278363851;
   fWeightMatrix0to1[6][9] = 1.29908631191454;
   fWeightMatrix0to1[7][9] = -0.0619240560366677;
   fWeightMatrix0to1[8][9] = 1.18988308083558;
   fWeightMatrix0to1[9][9] = 1.41210289891895;
   fWeightMatrix0to1[10][9] = -0.927156889237349;
   fWeightMatrix0to1[11][9] = 1.16306511236074;
   fWeightMatrix0to1[12][9] = 1.00129397919515;
   fWeightMatrix0to1[13][9] = 1.10572385197372;
   fWeightMatrix0to1[14][9] = 1.82943159478522;
   fWeightMatrix0to1[15][9] = -0.815632760456117;
   fWeightMatrix0to1[16][9] = -0.265790694730626;
   fWeightMatrix0to1[17][9] = 0.477820676738163;
   fWeightMatrix0to1[0][10] = 0.153109347769336;
   fWeightMatrix0to1[1][10] = -0.907537779208496;
   fWeightMatrix0to1[2][10] = 0.26147296436838;
   fWeightMatrix0to1[3][10] = -2.01042472713369;
   fWeightMatrix0to1[4][10] = -1.75461390387242;
   fWeightMatrix0to1[5][10] = -0.319226662842699;
   fWeightMatrix0to1[6][10] = 0.834630846749243;
   fWeightMatrix0to1[7][10] = -0.645236454819888;
   fWeightMatrix0to1[8][10] = -0.486905021292335;
   fWeightMatrix0to1[9][10] = -1.12783402472198;
   fWeightMatrix0to1[10][10] = -0.922668775102536;
   fWeightMatrix0to1[11][10] = -0.468446643298405;
   fWeightMatrix0to1[12][10] = -0.964628653277911;
   fWeightMatrix0to1[13][10] = -0.609941677935238;
   fWeightMatrix0to1[14][10] = 0.208336788103441;
   fWeightMatrix0to1[15][10] = 0.300287234045733;
   fWeightMatrix0to1[16][10] = 0.173781394271615;
   fWeightMatrix0to1[17][10] = 0.217685288945372;
   fWeightMatrix0to1[0][11] = 0.523524062742163;
   fWeightMatrix0to1[1][11] = 1.5843808004329;
   fWeightMatrix0to1[2][11] = -2.23880973345519;
   fWeightMatrix0to1[3][11] = 2.39747306608869;
   fWeightMatrix0to1[4][11] = -1.96621699960963;
   fWeightMatrix0to1[5][11] = 1.00176855237679;
   fWeightMatrix0to1[6][11] = -0.884271021378383;
   fWeightMatrix0to1[7][11] = -1.93061094134765;
   fWeightMatrix0to1[8][11] = -0.405585115884979;
   fWeightMatrix0to1[9][11] = 2.30313608922143;
   fWeightMatrix0to1[10][11] = 0.677145089228341;
   fWeightMatrix0to1[11][11] = -0.73362676635226;
   fWeightMatrix0to1[12][11] = -1.01987431120443;
   fWeightMatrix0to1[13][11] = -0.893716540507811;
   fWeightMatrix0to1[14][11] = -1.51437106479866;
   fWeightMatrix0to1[15][11] = 0.716054946256418;
   fWeightMatrix0to1[16][11] = -0.269842736820398;
   fWeightMatrix0to1[17][11] = 1.33487668761966;
   fWeightMatrix0to1[0][12] = -1.51682684424404;
   fWeightMatrix0to1[1][12] = 1.52884419646679;
   fWeightMatrix0to1[2][12] = 0.452922480702858;
   fWeightMatrix0to1[3][12] = 1.30992625800695;
   fWeightMatrix0to1[4][12] = 0.913503722792598;
   fWeightMatrix0to1[5][12] = -0.0722235944363721;
   fWeightMatrix0to1[6][12] = 0.126424376914786;
   fWeightMatrix0to1[7][12] = 1.00484762591947;
   fWeightMatrix0to1[8][12] = 0.715882711783702;
   fWeightMatrix0to1[9][12] = -0.414385119695323;
   fWeightMatrix0to1[10][12] = -0.656503309334049;
   fWeightMatrix0to1[11][12] = 1.20923722448229;
   fWeightMatrix0to1[12][12] = -1.21485789123287;
   fWeightMatrix0to1[13][12] = 0.0962244164057347;
   fWeightMatrix0to1[14][12] = -0.613076771862989;
   fWeightMatrix0to1[15][12] = 0.584322669588862;
   fWeightMatrix0to1[16][12] = 0.283947472390639;
   fWeightMatrix0to1[17][12] = -1.73375692571461;
   fWeightMatrix0to1[0][13] = 0.0660762553438544;
   fWeightMatrix0to1[1][13] = 2.15804833888025;
   fWeightMatrix0to1[2][13] = -0.490549503508516;
   fWeightMatrix0to1[3][13] = -0.920002762024038;
   fWeightMatrix0to1[4][13] = -0.779647634738161;
   fWeightMatrix0to1[5][13] = 1.07214517251372;
   fWeightMatrix0to1[6][13] = -0.24827282665736;
   fWeightMatrix0to1[7][13] = 1.36492922780356;
   fWeightMatrix0to1[8][13] = -0.174364028959919;
   fWeightMatrix0to1[9][13] = 1.37974545680042;
   fWeightMatrix0to1[10][13] = -0.0605262252073217;
   fWeightMatrix0to1[11][13] = -1.39981826187243;
   fWeightMatrix0to1[12][13] = 0.505494782382333;
   fWeightMatrix0to1[13][13] = 0.748453857791904;
   fWeightMatrix0to1[14][13] = -1.01954629935954;
   fWeightMatrix0to1[15][13] = -1.5321198736951;
   fWeightMatrix0to1[16][13] = -0.820269137027195;
   fWeightMatrix0to1[17][13] = 0.571319029868916;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.174631870945108;
   fWeightMatrix1to2[0][1] = 0.0509082510740003;
   fWeightMatrix1to2[0][2] = 0.853069295634662;
   fWeightMatrix1to2[0][3] = -0.22582116769488;
   fWeightMatrix1to2[0][4] = 0.165828098243599;
   fWeightMatrix1to2[0][5] = 1.05617712010229;
   fWeightMatrix1to2[0][6] = -0.653295366161043;
   fWeightMatrix1to2[0][7] = -0.0871740547307977;
   fWeightMatrix1to2[0][8] = 0.130040006338815;
   fWeightMatrix1to2[0][9] = 0.18925149125117;
   fWeightMatrix1to2[0][10] = -0.610797556230747;
   fWeightMatrix1to2[0][11] = -0.278410138019621;
   fWeightMatrix1to2[0][12] = -0.156249764119664;
   fWeightMatrix1to2[0][13] = 0.237448559884243;
   fWeightMatrix1to2[0][14] = -0.499671310069002;
   fWeightMatrix1to2[0][15] = -0.19864580344479;
   fWeightMatrix1to2[0][16] = 1.74508897599548;
   fWeightMatrix1to2[0][17] = 0.271161909144103;
   fWeightMatrix1to2[0][18] = 0.578801902130929;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0.0869567543268;
   fMax_1[0][0] = 58682.0507812;
   fMin_1[1][0] = 0.0869567543268;
   fMax_1[1][0] = 58682.0507812;
   fMin_1[2][0] = 0.0869567543268;
   fMax_1[2][0] = 58682.0507812;
   fMin_1[0][1] = 15.0001068115;
   fMax_1[0][1] = 446.446594238;
   fMin_1[1][1] = 15.0001068115;
   fMax_1[1][1] = 446.446594238;
   fMin_1[2][1] = 15.0001068115;
   fMax_1[2][1] = 446.446594238;
   fMin_1[0][2] = 20.0247249603;
   fMax_1[0][2] = 897.134277344;
   fMin_1[1][2] = 20.0247249603;
   fMax_1[1][2] = 923.271057129;
   fMin_1[2][2] = 20.0247249603;
   fMax_1[2][2] = 923.271057129;
   fMin_1[0][3] = 0.00320380693302;
   fMax_1[0][3] = 3.1414437294;
   fMin_1[1][3] = 0.00320380693302;
   fMax_1[1][3] = 3.14152598381;
   fMin_1[2][3] = 0.00320380693302;
   fMax_1[2][3] = 3.14152598381;
   fMin_1[0][4] = 3.65972518921e-05;
   fMax_1[0][4] = 3.14153695107;
   fMin_1[1][4] = 3.65972518921e-05;
   fMax_1[1][4] = 3.14153695107;
   fMin_1[2][4] = 3.65972518921e-05;
   fMax_1[2][4] = 3.14153695107;
   fMin_1[0][5] = 0.000435188296251;
   fMax_1[0][5] = 3124.58056641;
   fMin_1[1][5] = 0.000435188296251;
   fMax_1[1][5] = 3124.58056641;
   fMin_1[2][5] = 0.000435188296251;
   fMax_1[2][5] = 3124.58056641;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 103.247169495;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 103.247169495;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 103.247169495;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 89.6219711304;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 89.6219711304;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 89.6219711304;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 11;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 11;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = -4;
   fMax_1[0][12] = 4;
   fMin_1[1][12] = -4;
   fMax_1[1][12] = 4;
   fMin_1[2][12] = -4;
   fMax_1[2][12] = 4;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
