// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.0.1         [262145]
ROOT Release   : 5.24/00       [333824]
Creator        : twig
Date           : Thu Dec 10 11:27:45 2009
Host           : Darwin dyn1205-245.wlan.ic.ac.uk 10.0.0 Darwin Kernel Version 10.0.0: Fri Jul 31 22:47:34 PDT 2009; root:xnu-1456.1.25~1/RELEASE_I386 i386
Dir            : /Users/twig/gbmsci/tmva
Training events: 11437
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "0.000000e+00" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
lv_met_Et                     lv_met_Et                     lv_met_Et                     lv_met_Et                                                       'F'    [0.182211950421,58682.0507812]
lv_electron_Et                lv_electron_Et                lv_electron_Et                lv_electron_Et                                                  'F'    [15.0001068115,446.446594238]
lv_tau_Et                     lv_tau_Et                     lv_tau_Et                     lv_tau_Et                                                       'F'    [20.0108680725,2125.7890625]
dphielectau                   dphielectau                   dphielectau                   dphielectau                                                     'F'    [0.00685238838196,3.1414911747]
dphielecmet                   dphielecmet                   dphielecmet                   dphielecmet                                                     'F'    [4.64916192868e-05,3.14153695107]
mtelecmet                     mtelecmet                     mtelecmet                     mtelecmet                                                       'F'    [0.00032126007136,3124.58056641]
electronEcalIso               electronEcalIso               electronEcalIso               electronEcalIso                                                 'F'    [0,103.247169495]
electronTrackIso              electronTrackIso              electronTrackIso              electronTrackIso                                                'F'    [0,89.6219711304]
tauTrack                      tauTrack                      tauTrack                      tauTrack                                                        'I'    [0,11]
tauLeadTrk                    tauLeadTrk                    tauLeadTrk                    tauLeadTrk                                                      'I'    [0,1]
tauECALIso                    tauECALIso                    tauECALIso                    tauECALIso                                                      'I'    [0,1]
tauElectron                   tauElectron                   tauElectron                   tauElectron                                                     'I'    [0,1]
tauCharge                     tauCharge                     tauCharge                     tauCharge                                                       'I'    [-4,4]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "lv_met_Et", "lv_electron_Et", "lv_tau_Et", "dphielectau", "dphielecmet", "mtelecmet", "electronEcalIso", "electronTrackIso", "tauTrack", "tauLeadTrk", "tauECALIso", "tauElectron", "tauCharge" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'I';
      fType[9] = 'I';
      fType[10] = 'I';
      fType[11] = 'I';
      fType[12] = 'I';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][13];
   double fMax_1[3][13];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[19][14];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][19];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 14; fWeights[0] = new double[14]; 
   fLayerSize[1] = 19; fWeights[1] = new double[19]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.103642190942066;
   fWeightMatrix0to1[1][0] = -0.0431801762562031;
   fWeightMatrix0to1[2][0] = 1.57374470042496;
   fWeightMatrix0to1[3][0] = 1.06884473818347;
   fWeightMatrix0to1[4][0] = 1.09169077464525;
   fWeightMatrix0to1[5][0] = 1.34981557927201;
   fWeightMatrix0to1[6][0] = 1.10372799958285;
   fWeightMatrix0to1[7][0] = -1.61811662924681;
   fWeightMatrix0to1[8][0] = -1.4995018189142;
   fWeightMatrix0to1[9][0] = 1.36591992329459;
   fWeightMatrix0to1[10][0] = -1.64868909358615;
   fWeightMatrix0to1[11][0] = -0.0393820795632332;
   fWeightMatrix0to1[12][0] = -0.839167014000088;
   fWeightMatrix0to1[13][0] = -1.32701825480207;
   fWeightMatrix0to1[14][0] = 0.0664568209670063;
   fWeightMatrix0to1[15][0] = 1.80741468159284;
   fWeightMatrix0to1[16][0] = -0.990248470564018;
   fWeightMatrix0to1[17][0] = -2.05534005374831;
   fWeightMatrix0to1[0][1] = 0.0146604645839859;
   fWeightMatrix0to1[1][1] = 7.0199702406019;
   fWeightMatrix0to1[2][1] = -0.97001332534685;
   fWeightMatrix0to1[3][1] = 4.99408530189532;
   fWeightMatrix0to1[4][1] = -2.29460687058026;
   fWeightMatrix0to1[5][1] = 0.286657935365006;
   fWeightMatrix0to1[6][1] = 0.803757159072856;
   fWeightMatrix0to1[7][1] = 1.96846965035676;
   fWeightMatrix0to1[8][1] = -2.75030142759068;
   fWeightMatrix0to1[9][1] = -2.07073860541791;
   fWeightMatrix0to1[10][1] = 5.68808417820476;
   fWeightMatrix0to1[11][1] = 0.296975789055139;
   fWeightMatrix0to1[12][1] = -2.15033315055183;
   fWeightMatrix0to1[13][1] = 0.792704037136405;
   fWeightMatrix0to1[14][1] = -0.579007048986153;
   fWeightMatrix0to1[15][1] = -0.595949766649341;
   fWeightMatrix0to1[16][1] = 0.15939413772202;
   fWeightMatrix0to1[17][1] = 0.662446111948628;
   fWeightMatrix0to1[0][2] = 0.830096239647171;
   fWeightMatrix0to1[1][2] = -0.639703681054889;
   fWeightMatrix0to1[2][2] = 0.693499243604528;
   fWeightMatrix0to1[3][2] = -0.332527179999627;
   fWeightMatrix0to1[4][2] = -1.74925168998241;
   fWeightMatrix0to1[5][2] = 0.0100408555251927;
   fWeightMatrix0to1[6][2] = -2.06758212561215;
   fWeightMatrix0to1[7][2] = -0.544924025330614;
   fWeightMatrix0to1[8][2] = -1.321341274299;
   fWeightMatrix0to1[9][2] = 2.01867038121416;
   fWeightMatrix0to1[10][2] = 4.14359341490999;
   fWeightMatrix0to1[11][2] = -1.40745864391399;
   fWeightMatrix0to1[12][2] = 0.0862626491433584;
   fWeightMatrix0to1[13][2] = 0.844871490632173;
   fWeightMatrix0to1[14][2] = 1.5312847468887;
   fWeightMatrix0to1[15][2] = 0.322057034675511;
   fWeightMatrix0to1[16][2] = 1.98389995786246;
   fWeightMatrix0to1[17][2] = -0.696069378531076;
   fWeightMatrix0to1[0][3] = 0.815812072567105;
   fWeightMatrix0to1[1][3] = 3.16104106649963;
   fWeightMatrix0to1[2][3] = 0.343270293406144;
   fWeightMatrix0to1[3][3] = 2.47323003212945;
   fWeightMatrix0to1[4][3] = -0.412676335349754;
   fWeightMatrix0to1[5][3] = 0.363268431659176;
   fWeightMatrix0to1[6][3] = 1.7778062105868;
   fWeightMatrix0to1[7][3] = -1.74563076834335;
   fWeightMatrix0to1[8][3] = -1.65370313184894;
   fWeightMatrix0to1[9][3] = -1.86701783254103;
   fWeightMatrix0to1[10][3] = 1.8739714056401;
   fWeightMatrix0to1[11][3] = 0.0376030536661987;
   fWeightMatrix0to1[12][3] = -0.624557997896985;
   fWeightMatrix0to1[13][3] = -1.04564430183385;
   fWeightMatrix0to1[14][3] = -0.678131859839947;
   fWeightMatrix0to1[15][3] = 1.1940807934623;
   fWeightMatrix0to1[16][3] = -0.302561807155502;
   fWeightMatrix0to1[17][3] = -1.49268989198898;
   fWeightMatrix0to1[0][4] = 0.0688323723764619;
   fWeightMatrix0to1[1][4] = -0.0320237888617271;
   fWeightMatrix0to1[2][4] = -1.37942860032006;
   fWeightMatrix0to1[3][4] = 1.52359967028546;
   fWeightMatrix0to1[4][4] = 0.84199758994164;
   fWeightMatrix0to1[5][4] = 0.139596831361604;
   fWeightMatrix0to1[6][4] = 0.711593278280976;
   fWeightMatrix0to1[7][4] = -1.24361542541135;
   fWeightMatrix0to1[8][4] = 0.196692461834287;
   fWeightMatrix0to1[9][4] = 1.21397698259746;
   fWeightMatrix0to1[10][4] = 0.30483661688887;
   fWeightMatrix0to1[11][4] = 0.315192448348618;
   fWeightMatrix0to1[12][4] = 3.07477260292141;
   fWeightMatrix0to1[13][4] = 0.185153886392479;
   fWeightMatrix0to1[14][4] = 0.216802518545524;
   fWeightMatrix0to1[15][4] = 0.62486823178004;
   fWeightMatrix0to1[16][4] = 0.00519149107759231;
   fWeightMatrix0to1[17][4] = 1.18577113840849;
   fWeightMatrix0to1[0][5] = -1.69984509366022;
   fWeightMatrix0to1[1][5] = -3.55370269100721;
   fWeightMatrix0to1[2][5] = 0.722396890267876;
   fWeightMatrix0to1[3][5] = 1.1239439628663;
   fWeightMatrix0to1[4][5] = -1.63337441181561;
   fWeightMatrix0to1[5][5] = -1.13352967664049;
   fWeightMatrix0to1[6][5] = -1.70807197114565;
   fWeightMatrix0to1[7][5] = -1.99967631077139;
   fWeightMatrix0to1[8][5] = -0.819112589179048;
   fWeightMatrix0to1[9][5] = 0.0633782630906278;
   fWeightMatrix0to1[10][5] = -1.17998298478854;
   fWeightMatrix0to1[11][5] = 2.26992079514677;
   fWeightMatrix0to1[12][5] = 1.4084649576988;
   fWeightMatrix0to1[13][5] = -1.25580587420889;
   fWeightMatrix0to1[14][5] = 0.0941250463569929;
   fWeightMatrix0to1[15][5] = 1.98657595371567;
   fWeightMatrix0to1[16][5] = -1.49993617442131;
   fWeightMatrix0to1[17][5] = -1.77760528296401;
   fWeightMatrix0to1[0][6] = -1.15887384350913;
   fWeightMatrix0to1[1][6] = -0.189293581433902;
   fWeightMatrix0to1[2][6] = -0.384175572335475;
   fWeightMatrix0to1[3][6] = 2.71204101026938;
   fWeightMatrix0to1[4][6] = -0.598091645429368;
   fWeightMatrix0to1[5][6] = -1.51449758802372;
   fWeightMatrix0to1[6][6] = 1.61930845016691;
   fWeightMatrix0to1[7][6] = -1.11236066499472;
   fWeightMatrix0to1[8][6] = 0.887888679349761;
   fWeightMatrix0to1[9][6] = 0.669676111029831;
   fWeightMatrix0to1[10][6] = 0.440157974369206;
   fWeightMatrix0to1[11][6] = -0.592107786697744;
   fWeightMatrix0to1[12][6] = 1.39827874211655;
   fWeightMatrix0to1[13][6] = -1.56513594094423;
   fWeightMatrix0to1[14][6] = -1.08195220221731;
   fWeightMatrix0to1[15][6] = 1.55168873109842;
   fWeightMatrix0to1[16][6] = -0.128596089083597;
   fWeightMatrix0to1[17][6] = -1.79973099304857;
   fWeightMatrix0to1[0][7] = -0.841165005096852;
   fWeightMatrix0to1[1][7] = -0.543992630110826;
   fWeightMatrix0to1[2][7] = -0.602479211887101;
   fWeightMatrix0to1[3][7] = 0.862457805138114;
   fWeightMatrix0to1[4][7] = 0.278684351271878;
   fWeightMatrix0to1[5][7] = -1.95875399807411;
   fWeightMatrix0to1[6][7] = -1.63910501545302;
   fWeightMatrix0to1[7][7] = -0.205121458491081;
   fWeightMatrix0to1[8][7] = 1.16693669938988;
   fWeightMatrix0to1[9][7] = 1.13036212646097;
   fWeightMatrix0to1[10][7] = 0.0409311027403683;
   fWeightMatrix0to1[11][7] = 0.05891480968844;
   fWeightMatrix0to1[12][7] = 0.285950121024929;
   fWeightMatrix0to1[13][7] = -2.14998850856982;
   fWeightMatrix0to1[14][7] = -1.52525379088719;
   fWeightMatrix0to1[15][7] = 1.82575370808827;
   fWeightMatrix0to1[16][7] = -0.424006617251475;
   fWeightMatrix0to1[17][7] = -1.7718104493748;
   fWeightMatrix0to1[0][8] = -0.452373409627801;
   fWeightMatrix0to1[1][8] = -3.44813346885406;
   fWeightMatrix0to1[2][8] = 0.839952877046654;
   fWeightMatrix0to1[3][8] = -4.23976561593261;
   fWeightMatrix0to1[4][8] = -0.499161790683416;
   fWeightMatrix0to1[5][8] = -1.19631518511625;
   fWeightMatrix0to1[6][8] = 0.635266728074504;
   fWeightMatrix0to1[7][8] = 0.830902454419118;
   fWeightMatrix0to1[8][8] = 2.66879126009391;
   fWeightMatrix0to1[9][8] = 0.491255025799998;
   fWeightMatrix0to1[10][8] = -3.72510829380731;
   fWeightMatrix0to1[11][8] = -0.938655120231165;
   fWeightMatrix0to1[12][8] = 0.960802869482115;
   fWeightMatrix0to1[13][8] = -0.10149530445127;
   fWeightMatrix0to1[14][8] = 0.897993772675453;
   fWeightMatrix0to1[15][8] = 1.79128862843855;
   fWeightMatrix0to1[16][8] = 0.479748417838702;
   fWeightMatrix0to1[17][8] = -0.177815912620972;
   fWeightMatrix0to1[0][9] = -1.15982286022328;
   fWeightMatrix0to1[1][9] = 0.297176588737437;
   fWeightMatrix0to1[2][9] = -0.0582050122770431;
   fWeightMatrix0to1[3][9] = 0.842506377628216;
   fWeightMatrix0to1[4][9] = 0.438700124843753;
   fWeightMatrix0to1[5][9] = -1.29466782899027;
   fWeightMatrix0to1[6][9] = -0.51485722078545;
   fWeightMatrix0to1[7][9] = -1.23353146194659;
   fWeightMatrix0to1[8][9] = 0.793853167635788;
   fWeightMatrix0to1[9][9] = -0.178947466191932;
   fWeightMatrix0to1[10][9] = 0.779748767786761;
   fWeightMatrix0to1[11][9] = -0.150716647425799;
   fWeightMatrix0to1[12][9] = -0.629451814323455;
   fWeightMatrix0to1[13][9] = -0.264381867594695;
   fWeightMatrix0to1[14][9] = -0.121862898894713;
   fWeightMatrix0to1[15][9] = 1.02725695431749;
   fWeightMatrix0to1[16][9] = -0.0686777013119245;
   fWeightMatrix0to1[17][9] = -0.330406227505984;
   fWeightMatrix0to1[0][10] = -1.24888096206789;
   fWeightMatrix0to1[1][10] = -0.0519305698334787;
   fWeightMatrix0to1[2][10] = 0.258010324077968;
   fWeightMatrix0to1[3][10] = 0.114649787487968;
   fWeightMatrix0to1[4][10] = 0.800041370002722;
   fWeightMatrix0to1[5][10] = 1.92509059502259;
   fWeightMatrix0to1[6][10] = 0.594188768189228;
   fWeightMatrix0to1[7][10] = -1.569088125458;
   fWeightMatrix0to1[8][10] = 1.01881330258309;
   fWeightMatrix0to1[9][10] = 0.0735626262276676;
   fWeightMatrix0to1[10][10] = 0.699403519953251;
   fWeightMatrix0to1[11][10] = -0.167539204191727;
   fWeightMatrix0to1[12][10] = 0.159059885290822;
   fWeightMatrix0to1[13][10] = 0.472719418029816;
   fWeightMatrix0to1[14][10] = 1.89113916502187;
   fWeightMatrix0to1[15][10] = -1.1309400853473;
   fWeightMatrix0to1[16][10] = 0.06437127934774;
   fWeightMatrix0to1[17][10] = 0.888254709785578;
   fWeightMatrix0to1[0][11] = -1.50201701864017;
   fWeightMatrix0to1[1][11] = 3.62521253198204;
   fWeightMatrix0to1[2][11] = 0.0694696992053935;
   fWeightMatrix0to1[3][11] = -3.2205410012728;
   fWeightMatrix0to1[4][11] = 0.548974080681014;
   fWeightMatrix0to1[5][11] = 0.270843214187476;
   fWeightMatrix0to1[6][11] = -0.71712467432273;
   fWeightMatrix0to1[7][11] = 0.258137186378333;
   fWeightMatrix0to1[8][11] = 2.13263785236945;
   fWeightMatrix0to1[9][11] = -1.55975102099009;
   fWeightMatrix0to1[10][11] = -0.097630245369971;
   fWeightMatrix0to1[11][11] = 0.298551033091269;
   fWeightMatrix0to1[12][11] = -1.18669123092044;
   fWeightMatrix0to1[13][11] = 0.780596674127099;
   fWeightMatrix0to1[14][11] = -0.0415183698075475;
   fWeightMatrix0to1[15][11] = -0.166496682395026;
   fWeightMatrix0to1[16][11] = -0.318590148238112;
   fWeightMatrix0to1[17][11] = 1.45668066334315;
   fWeightMatrix0to1[0][12] = 0.507197616845673;
   fWeightMatrix0to1[1][12] = -0.0533425470834837;
   fWeightMatrix0to1[2][12] = -0.0540228239528319;
   fWeightMatrix0to1[3][12] = -0.524001044757913;
   fWeightMatrix0to1[4][12] = -0.260177791780639;
   fWeightMatrix0to1[5][12] = 0.178557093043694;
   fWeightMatrix0to1[6][12] = -0.467167464252877;
   fWeightMatrix0to1[7][12] = -0.492048224638615;
   fWeightMatrix0to1[8][12] = -0.643023015768018;
   fWeightMatrix0to1[9][12] = 0.321044175291124;
   fWeightMatrix0to1[10][12] = 0.412968606337888;
   fWeightMatrix0to1[11][12] = 0.269855858811097;
   fWeightMatrix0to1[12][12] = 0.619553248134556;
   fWeightMatrix0to1[13][12] = -1.89889783423516;
   fWeightMatrix0to1[14][12] = -0.428451116950551;
   fWeightMatrix0to1[15][12] = 1.17551760254736;
   fWeightMatrix0to1[16][12] = 0.234067584124218;
   fWeightMatrix0to1[17][12] = 0.39080392977706;
   fWeightMatrix0to1[0][13] = -0.477726403299334;
   fWeightMatrix0to1[1][13] = -0.816708362981479;
   fWeightMatrix0to1[2][13] = 1.14572694374812;
   fWeightMatrix0to1[3][13] = 1.50149035992513;
   fWeightMatrix0to1[4][13] = -1.57210412701962;
   fWeightMatrix0to1[5][13] = -0.944712776206396;
   fWeightMatrix0to1[6][13] = 2.17965767526941;
   fWeightMatrix0to1[7][13] = 1.5178812566186;
   fWeightMatrix0to1[8][13] = 0.214966684002162;
   fWeightMatrix0to1[9][13] = 1.0633631049725;
   fWeightMatrix0to1[10][13] = 0.719230522383499;
   fWeightMatrix0to1[11][13] = -0.451719865021883;
   fWeightMatrix0to1[12][13] = -1.76176562354509;
   fWeightMatrix0to1[13][13] = 1.83539156215863;
   fWeightMatrix0to1[14][13] = 1.87235084646079;
   fWeightMatrix0to1[15][13] = -1.18732176953218;
   fWeightMatrix0to1[16][13] = -0.546531760246727;
   fWeightMatrix0to1[17][13] = 1.53401339359003;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.174823466231135;
   fWeightMatrix1to2[0][1] = 0.388015679080752;
   fWeightMatrix1to2[0][2] = -0.389900454472527;
   fWeightMatrix1to2[0][3] = 0.492616316364405;
   fWeightMatrix1to2[0][4] = 0.841192001197176;
   fWeightMatrix1to2[0][5] = 0.267330153174748;
   fWeightMatrix1to2[0][6] = -0.756803813259073;
   fWeightMatrix1to2[0][7] = 0.286292963801509;
   fWeightMatrix1to2[0][8] = -0.187881719264661;
   fWeightMatrix1to2[0][9] = 0.637583466263329;
   fWeightMatrix1to2[0][10] = 0.419992205516327;
   fWeightMatrix1to2[0][11] = -0.516724267941403;
   fWeightMatrix1to2[0][12] = -0.532293268998782;
   fWeightMatrix1to2[0][13] = -0.907678279234611;
   fWeightMatrix1to2[0][14] = -0.127606079522216;
   fWeightMatrix1to2[0][15] = -0.435657616257208;
   fWeightMatrix1to2[0][16] = 0.225670639353079;
   fWeightMatrix1to2[0][17] = -1.45798384495263;
   fWeightMatrix1to2[0][18] = 1.50818996020313;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   fMin_1[0][0] = 0.278129458427;
   fMax_1[0][0] = 58682.0507812;
   fMin_1[1][0] = 0.182211950421;
   fMax_1[1][0] = 58682.0507812;
   fMin_1[2][0] = 0.182211950421;
   fMax_1[2][0] = 58682.0507812;
   fMin_1[0][1] = 15.0001068115;
   fMax_1[0][1] = 446.446594238;
   fMin_1[1][1] = 15.0001068115;
   fMax_1[1][1] = 446.446594238;
   fMin_1[2][1] = 15.0001068115;
   fMax_1[2][1] = 446.446594238;
   fMin_1[0][2] = 20.0247249603;
   fMax_1[0][2] = 897.134277344;
   fMin_1[1][2] = 20.0108680725;
   fMax_1[1][2] = 2125.7890625;
   fMin_1[2][2] = 20.0108680725;
   fMax_1[2][2] = 2125.7890625;
   fMin_1[0][3] = 0.0114453295246;
   fMax_1[0][3] = 3.1414437294;
   fMin_1[1][3] = 0.00685238838196;
   fMax_1[1][3] = 3.1414911747;
   fMin_1[2][3] = 0.00685238838196;
   fMax_1[2][3] = 3.1414911747;
   fMin_1[0][4] = 6.89029693604e-05;
   fMax_1[0][4] = 3.14153695107;
   fMin_1[1][4] = 4.64916192868e-05;
   fMax_1[1][4] = 3.14153695107;
   fMin_1[2][4] = 4.64916192868e-05;
   fMax_1[2][4] = 3.14153695107;
   fMin_1[0][5] = 0.000751251238398;
   fMax_1[0][5] = 3124.58056641;
   fMin_1[1][5] = 0.00032126007136;
   fMax_1[1][5] = 3124.58056641;
   fMin_1[2][5] = 0.00032126007136;
   fMax_1[2][5] = 3124.58056641;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 103.247169495;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 103.247169495;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 103.247169495;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 89.6219711304;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 89.6219711304;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 89.6219711304;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 11;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 11;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 1;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 1;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 1;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 1;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = -4;
   fMax_1[0][12] = 4;
   fMin_1[1][12] = -4;
   fMax_1[1][12] = 4;
   fMin_1[2][12] = -4;
   fMax_1[2][12] = 4;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
   else cls = 2;
}
   for (int ivar=0;ivar<13;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[ivar] = (iv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
